/**
 * Built-in agent tool `name` values for gateway admin UI (disable toggles).
 * Extension tools are not listed; users can still add arbitrary strings in config.
 */
export const GATEWAY_BUILTIN_TOOL_IDS = [
  'read_file',
  'write_file',
  'apply_patch',
  'list_dir',
  'grep',
  'find',
  'exec_command',
  'update_plan',
  'session_status',
  'dreaming',
  'tool_manual',
  'clarify',
  'todo',
  'skills_list',
  'skill_view',
  'skill_manage',
  'web_search',
  'web_fetch',
  'web_extract',
  'send_message',
  'send_media',
  'read_media',
  'create_share',
  'text_to_speech',
  'memory_search',
  'memory_get',
  'curated_memory',
  'session_search',
  'automation',
  'workflow',
  'delegate_task',
  'execute_code',
  'image',
  'image_generate',
  'create_desktop_pet',
  'browser_use',
  'extensions',
  'bundle-mcp',
] as const;

export type GatewayBuiltinToolId = (typeof GATEWAY_BUILTIN_TOOL_IDS)[number];
