packages:
  - '.'
  - 'extensions/*'
  - 'packages/*'
  - 'web'

allowBuilds:
  '@google/genai': true
  '@swc/core': true
  '@vscode/ripgrep': true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
