import type { ConnectorDefinition } from './types.js';

const BUILTIN_CONNECTOR_BACKGROUNDS: Record<string, string> = {
  'brave-search': '#FFF4ED',
  fetch: '#E8F3FF',
  filesystem: '#FFF7E6',
  github: '#FFFFFF',
  memory: '#F3E8FF',
  playwright: '#FFFFFF',
  'sequential-thinking': '#ECFDF5',
  time: '#ECFEFF',
};

function builtinBranding(id: string): NonNullable<ConnectorDefinition['branding']> {
  return {
    logoUrl: `/connector-icons/${id}.svg`,
    source: 'builtin',
    backgroundColor: BUILTIN_CONNECTOR_BACKGROUNDS[id] ?? '#FFFFFF',
  };
}

export const BUILTIN_CONNECTORS: readonly ConnectorDefinition[] = [
  {
    id: 'fetch',
    version: '1.0.0',
    displayName: 'Fetch',
    description: 'Fetch and read web pages through the official MCP fetch server.',
    category: 'docs',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('fetch'),
    capabilities: ['tools', 'runtime.mcp.stdio'],
    tags: ['web', 'docs', 'http'],
    auth: { mode: 'none' },
    setup: {},
    runtime: {
      type: 'mcp',
      serverId: 'fetch',
      serverTemplate: {
        command: 'uvx',
        args: ['mcp-server-fetch'],
      },
    },
  },
  {
    id: 'filesystem',
    version: '1.0.0',
    displayName: 'Filesystem',
    description: 'Read and search files from an explicitly selected local directory.',
    category: 'docs',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('filesystem'),
    capabilities: ['tools', 'resources', 'runtime.mcp.stdio'],
    tags: ['files', 'local', 'docs'],
    auth: { mode: 'none' },
    setup: {
      config: [
        {
          key: 'rootPath',
          label: 'Allowed directory',
          type: 'path',
          required: true,
          placeholder: '/Users/you/project',
          description: 'The only directory this connector can expose to the MCP runtime.',
        },
      ],
    },
    runtime: {
      type: 'mcp',
      serverId: 'filesystem',
      serverTemplate: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '{{config.rootPath}}'],
      },
    },
  },
  {
    id: 'time',
    version: '1.0.0',
    displayName: 'Time',
    description: 'Convert time zones and answer current-time questions through an MCP time server.',
    category: 'automation',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('time'),
    capabilities: ['tools', 'runtime.mcp.stdio'],
    tags: ['time', 'timezone', 'utility'],
    auth: { mode: 'none' },
    setup: {},
    runtime: {
      type: 'mcp',
      serverId: 'time',
      serverTemplate: {
        command: 'uvx',
        args: ['mcp-server-time'],
      },
    },
  },
  {
    id: 'playwright',
    version: '1.0.0',
    displayName: 'Playwright',
    description: 'Automate and inspect browser pages through the official Playwright MCP server.',
    category: 'browser',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('playwright'),
    capabilities: ['tools', 'runtime.mcp.stdio'],
    tags: ['browser', 'automation', 'testing'],
    auth: { mode: 'none' },
    setup: {},
    runtime: {
      type: 'mcp',
      serverId: 'playwright',
      serverTemplate: {
        command: 'npx',
        args: ['-y', '@playwright/mcp@latest'],
      },
    },
  },
  {
    id: 'github',
    version: '2.0.0',
    displayName: 'GitHub',
    description: 'Work with GitHub repositories, issues, pull requests, and code search.',
    category: 'code',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('github'),
    capabilities: ['tools', 'auth.oauth', 'runtime.mcp.streamableHttp'],
    tags: ['code', 'repository', 'issues'],
    auth: { mode: 'oauth', provider: 'github-app', installPhase: 'before_install' },
    setup: {},
    runtime: {
      type: 'mcp',
      serverId: 'github',
      serverTemplate: {
        url: 'https://api.githubcopilot.com/mcp/',
        transport: 'streamable-http',
        xopcAuth: { provider: 'github-app' },
      },
    },
  },
  {
    id: 'memory',
    version: '1.0.0',
    displayName: 'Memory',
    description: 'Give the agent a simple MCP knowledge graph memory store.',
    category: 'data',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('memory'),
    capabilities: ['tools', 'resources', 'runtime.mcp.stdio', 'memory_source'],
    tags: ['memory', 'knowledge', 'personalization'],
    auth: { mode: 'none' },
    setup: {},
    runtime: {
      type: 'mcp',
      serverId: 'memory',
      serverTemplate: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-memory'],
      },
    },
  },
  {
    id: 'sequential-thinking',
    version: '1.0.0',
    displayName: 'Sequential Thinking',
    description: 'Add a structured reasoning scratchpad MCP server for multi-step tasks.',
    category: 'automation',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('sequential-thinking'),
    capabilities: ['tools', 'runtime.mcp.stdio'],
    tags: ['reasoning', 'planning', 'utility'],
    auth: { mode: 'none' },
    setup: {},
    runtime: {
      type: 'mcp',
      serverId: 'sequential-thinking',
      serverTemplate: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
      },
    },
  },
  {
    id: 'brave-search',
    version: '1.0.0',
    displayName: 'Brave Search',
    description: 'Search the web through the Brave Search MCP server.',
    category: 'docs',
    kind: 'mcp',
    source: 'builtin',
    branding: builtinBranding('brave-search'),
    capabilities: ['tools', 'auth.apiKey', 'runtime.mcp.stdio'],
    tags: ['search', 'web', 'research'],
    auth: { mode: 'apiKey' },
    setup: {
      secrets: [
        {
          key: 'BRAVE_API_KEY',
          label: 'Brave API key',
          description: 'Stored in the xopc credential store and passed to the MCP server at runtime.',
          required: true,
        },
      ],
    },
    runtime: {
      type: 'mcp',
      serverId: 'brave-search',
      serverTemplate: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-brave-search'],
        env: {
          BRAVE_API_KEY: '{{secrets.BRAVE_API_KEY}}',
        },
      },
    },
  },
];
