import type { ConnectorDefinition } from './types.js';

const DINGTALK_MCP_VERSION = '1.1.21';

export const CHINA_CONNECTORS: readonly ConnectorDefinition[] = [
  {
    id: 'feishu-workspace', version: '1.0.96', displayName: '飞书办公',
    description: '连接飞书账号，搜索和读取文档、查询日程和联系人，并按权限创建日程。',
    category: 'docs', kind: 'cli', source: 'builtin', capabilities: ['tools'],
    benefits: ['understand', 'act'], tags: ['中国', 'Feishu', 'Lark', '飞书', '日历', '文档', '文件', '联系人'],
    branding: { logoUrl: '/channel-icons/feishu.svg', source: 'builtin' },
    verificationLevel: 'beta', auth: { mode: 'cli' }, setup: {},
    runtime: { type: 'cli', adapterId: 'lark', adapterVersion: '1', binaryVersion: '1.0.96' },
    permissions: { localExec: true, data: ['calendar', 'documents', 'contacts'], networkDomains: ['open.feishu.cn'] },
    integrationStrategy: { lane: 'native', workload: 'core', preferred: true },
  },
  {
    id: 'wecom-workspace', version: '1.3.0', displayName: '企业微信办公',
    description: '扫码连接企业微信，搜索和读取文档、查询联系人和待办，并按权限创建待办。',
    category: 'docs', kind: 'cli', source: 'builtin', capabilities: ['tools'],
    benefits: ['understand', 'act'], tags: ['中国', 'WeCom', '企业微信', '文档', '联系人', '待办'],
    verificationLevel: 'beta', auth: { mode: 'cli' }, setup: {},
    runtime: { type: 'cli', adapterId: 'wecom', adapterVersion: '1', binaryVersion: '1.3.0' },
    permissions: { localExec: true, data: ['documents', 'contacts', 'tasks'], networkDomains: ['qyapi.weixin.qq.com'] },
    integrationStrategy: { lane: 'native', workload: 'core', preferred: true },
  },
  {
    id: 'dingtalk-workspace',
    version: DINGTALK_MCP_VERSION,
    displayName: '钉钉办公',
    description: '连接钉钉通讯录、待办、日历、机器人和工作通知。',
    category: 'automation',
    kind: 'mcp',
    source: 'builtin',
    capabilities: ['tools', 'runtime.mcp.stdio', 'auth.apiKey'],
    benefits: ['act', 'reach'],
    tags: ['中国', '钉钉', '通讯录', '待办', '日历', '机器人'],
    branding: { logoUrl: '/connector-icons/dingtalk-mark.svg', source: 'builtin' },
    verificationLevel: 'verified',
    auth: { mode: 'apiKey' },
    setup: {
      links: [
        { label: '前往钉钉开发者后台创建应用', href: 'https://open-dev.dingtalk.com/fe/app', external: true },
      ],
      secrets: [
        { key: 'clientId', label: 'Client ID', description: '在钉钉应用的凭证与基础信息页复制。', required: true },
        { key: 'clientSecret', label: 'Client Secret', description: '与 Client ID 同一页面，仅保存在本机凭据存储。', required: true },
      ],
      config: [
        {
          key: 'activeProfiles',
          label: '启用服务',
          type: 'string',
          required: true,
          defaultValue: 'dingtalk-contacts,dingtalk-calendar,dingtalk-todo,dingtalk-robot',
          description: '逗号分隔的钉钉 MCP 服务列表。',
        },
      ],
    },
    runtime: {
      type: 'mcp',
      serverId: 'dingtalk_workspace',
      localPackage: {
        registry: 'npm',
        name: 'dingtalk-mcp',
        version: DINGTALK_MCP_VERSION,
      },
      serverTemplate: {
        command: 'npx',
        args: ['-y', `dingtalk-mcp@${DINGTALK_MCP_VERSION}`],
        env: {
          DINGTALK_Client_ID: '{{secrets.clientId}}',
          DINGTALK_Client_Secret: '{{secrets.clientSecret}}',
          ACTIVE_PROFILES: '{{config.activeProfiles}}',
        },
      },
    },
    permissions: {
      data: ['contacts', 'communications', 'calendar', 'tasks'],
      networkDomains: ['api.dingtalk.com', 'oapi.dingtalk.com'],
      localExec: true,
      filesystem: [],
    },
    integrationStrategy: { lane: 'mcp', workload: 'core', preferred: true },
  },
  {
    id: 'wps-cloud-docs',
    version: '2.0.0',
    displayName: 'WPS 365 云文档',
    description: '通过 WPS 官方 MCP 搜索云文档、读取内容与评论并管理分享权限。',
    category: 'docs',
    kind: 'mcp',
    source: 'builtin',
    capabilities: ['tools', 'runtime.mcp.streamableHttp', 'auth.apiKey'],
    benefits: ['understand', 'act'],
    tags: ['中国', 'WPS', '云文档', '知识库'],
    branding: { logoUrl: '/connector-icons/wps-docs.svg', source: 'builtin' },
    verificationLevel: 'verified',
    auth: { mode: 'apiKey' },
    setup: {
      links: [{ label: '查看 WPS 用户 Access Token 获取流程', href: 'https://open.wps.cn/documents/app-integration-dev/wps365/server/certification-authorization/user-authorization/flow', external: true }],
      secrets: [{ key: 'accessToken', label: '用户 Access Token', description: '需先创建 WPS 开放平台应用并完成用户授权。', required: true }],
    },
    runtime: {
      type: 'mcp',
      serverId: 'wps_cloud_docs',
      serverTemplate: {
        url: 'https://openapi.wps.cn/mcp/v2/kso-yundoc/message',
        transport: 'streamable-http',
        headers: { Authorization: 'Bearer {{secrets.accessToken}}' },
      },
    },
    permissions: {
      data: ['documents'],
      networkDomains: ['openapi.wps.cn'],
      localExec: false,
      filesystem: [],
    },
    integrationStrategy: { lane: 'mcp', workload: 'core', preferred: true },
  },
  {
    id: 'tencent-meeting',
    version: '1.0.0',
    displayName: '腾讯会议',
    description: '通过腾讯会议官方 MCP 查询、创建和管理个人会议。',
    category: 'automation',
    kind: 'mcp',
    source: 'builtin',
    capabilities: ['tools', 'runtime.mcp.streamableHttp', 'auth.apiKey'],
    benefits: ['understand', 'act'],
    tags: ['中国', '腾讯会议', '会议', '日程'],
    branding: { logoUrl: '/connector-icons/tencent-meeting-mark.svg', source: 'builtin' },
    verificationLevel: 'beta',
    auth: { mode: 'apiKey' },
    setup: {
      links: [{ label: '前往腾讯会议 MCP 获取说明', href: 'https://meeting.tencent.com/support/topic/2233/index.html', external: true }],
      secrets: [{ key: 'token', label: '腾讯会议 MCP Token', description: '目前个人账号可直接获取，企业账号需申请灰度。', required: true }],
    },
    runtime: {
      type: 'mcp',
      serverId: 'tencent_meeting',
      serverTemplate: {
        url: 'https://mcp.meeting.tencent.com/mcp',
        transport: 'streamable-http',
        headers: { 'X-Tencent-Meeting-Token': '{{secrets.token}}' },
      },
    },
    permissions: {
      data: ['calendar', 'meeting_records'],
      networkDomains: ['mcp.meeting.tencent.com'],
      localExec: false,
      filesystem: [],
    },
    integrationStrategy: { lane: 'mcp', workload: 'core', preferred: true },
  },
  {
    id: 'wps-calendar',
    version: '2.0.0',
    displayName: 'WPS 365 日历',
    description: '通过 WPS 官方 MCP 查询日程、管理参与人并创建会议安排。',
    category: 'automation',
    kind: 'mcp',
    source: 'builtin',
    capabilities: ['tools', 'runtime.mcp.streamableHttp', 'auth.apiKey'],
    benefits: ['understand', 'act'],
    tags: ['中国', 'WPS', '日历', '日程'],
    branding: { logoUrl: '/connector-icons/wps-calendar.svg', source: 'builtin' },
    verificationLevel: 'verified',
    auth: { mode: 'apiKey' },
    setup: {
      links: [{ label: '查看 WPS 用户 Access Token 获取流程', href: 'https://open.wps.cn/documents/app-integration-dev/wps365/server/certification-authorization/user-authorization/flow', external: true }],
      secrets: [{ key: 'accessToken', label: '用户 Access Token', description: '需先创建 WPS 开放平台应用并完成用户授权。', required: true }],
    },
    runtime: {
      type: 'mcp',
      serverId: 'wps_calendar',
      serverTemplate: {
        url: 'https://openapi.wps.cn/mcp/v2/kso-calendar/message',
        transport: 'streamable-http',
        headers: { Authorization: 'Bearer {{secrets.accessToken}}' },
      },
    },
    permissions: {
      data: ['calendar'],
      networkDomains: ['openapi.wps.cn'],
      localExec: false,
      filesystem: [],
    },
    integrationStrategy: { lane: 'mcp', workload: 'core', preferred: true },
  },
  {
    id: 'wps-mail',
    version: '2.0.0',
    displayName: 'WPS 365 邮箱',
    description: '通过 WPS 官方 MCP 搜索邮件、读取邮件并创建或发送草稿。',
    category: 'automation',
    kind: 'mcp',
    source: 'builtin',
    capabilities: ['tools', 'runtime.mcp.streamableHttp', 'auth.apiKey'],
    benefits: ['understand', 'act'],
    tags: ['中国', 'WPS', '邮箱', '邮件'],
    branding: { logoUrl: '/connector-icons/wps-mail.svg', source: 'builtin' },
    verificationLevel: 'verified',
    auth: { mode: 'apiKey' },
    setup: {
      links: [{ label: '查看 WPS 用户 Access Token 获取流程', href: 'https://open.wps.cn/documents/app-integration-dev/wps365/server/certification-authorization/user-authorization/flow', external: true }],
      secrets: [{ key: 'accessToken', label: '用户 Access Token', description: '需先创建 WPS 开放平台应用并完成用户授权。', required: true }],
    },
    runtime: {
      type: 'mcp',
      serverId: 'wps_mail',
      serverTemplate: {
        url: 'https://openapi.wps.cn/mcp/v2/kso-mail/message',
        transport: 'streamable-http',
        headers: { Authorization: 'Bearer {{secrets.accessToken}}' },
      },
    },
    permissions: {
      data: ['email'],
      networkDomains: ['openapi.wps.cn'],
      localExec: false,
      filesystem: [],
    },
    integrationStrategy: { lane: 'mcp', workload: 'core', preferred: true },
  },
];
