package ai.xopc.mobile

import androidx.compose.foundation.layout.safeDrawingPadding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.navigation3.runtime.entryProvider
import androidx.navigation3.runtime.rememberNavBackStack
import androidx.navigation3.ui.NavDisplay
import ai.xopc.mobile.ui.main.MainScreen
import ai.xopc.mobile.ui.main.GatewayViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.compose.runtime.getValue
import androidx.compose.runtime.LaunchedEffect

@Composable
fun MainNavigation(appearanceMode: String, onAppearanceModeChange: (String) -> Unit,
  colorScheme: String, onColorSchemeChange: (String) -> Unit,
  language: String, onLanguageChange: (String) -> Unit) {
  val backStack = rememberNavBackStack(Main)

  NavDisplay(
    backStack = backStack,
    onBack = { backStack.removeLastOrNull() },
    entryProvider =
      entryProvider {
        entry<Main> {
          val gateway: GatewayViewModel = viewModel()
          val connection by gateway.state.collectAsStateWithLifecycle()
          LaunchedEffect(gateway) { gateway.restore() }
          MainScreen(connection = connection, onPair = gateway::pair,
            onCancelPairing = gateway::cancelPairing,
            appearanceMode = appearanceMode, onAppearanceModeChange = onAppearanceModeChange,
            colorScheme = colorScheme, onColorSchemeChange = onColorSchemeChange,
            language = language, onLanguageChange = onLanguageChange,
            onConversationSearchChange = gateway::updateConversationSearch,
            onRefreshConversations = { gateway.loadConversations() },
            onLoadMoreConversations = gateway::loadMoreConversations,
            onLoadOlderHistory = gateway::loadOlderHistory,
            onSelectConversation = gateway::selectConversation, onCreateConversation = gateway::createConversation,
            onCreateProjectConversation = gateway::createProjectConversation,
            onSelectTaskChildConversation = gateway::selectTaskChildConversation,
            onCreateReferenceConversation = gateway::createConversationForReference,
            onReferenceRequestHandled = gateway::referenceRequestHandled,
            onDiscardDraft = gateway::discardLocalDraft,
            onBeginRename = gateway::beginRename, onRenameDraftChange = gateway::changeRenameDraft,
            onSaveRename = gateway::saveRename, onCancelRename = gateway::cancelRename,
            onTogglePin = gateway::togglePin,
            onToggleArchive = gateway::toggleArchive,
            onBatchConversations = gateway::batchConversations,
            onBeginConversationShare = gateway::beginConversationShare,
            onConfirmConversationShare = gateway::confirmConversationShare,
            onDismissConversationShare = gateway::dismissConversationShare,
            onScheduleDelete = gateway::scheduleDelete, onUndoDelete = gateway::undoDelete,
            onQuickDraftChange = gateway::changeQuickDraft, onQuickSubmit = gateway::submitQuickDraft,
            onAddQuickAttachment = gateway::addQuickAttachment,
            onAddCapturedQuickAttachment = gateway::addCapturedQuickAttachment,
            onRemoveQuickAttachment = gateway::removeQuickAttachment,
            onPreviewQuickImage = gateway::previewQuickImage,
            onPreviewQuickFile = gateway::previewQuickFile,
            onQuickNavigationHandled = gateway::quickNavigationHandled,
            onDraftChange = gateway::changeDraft, onSendMessage = gateway::sendMessage,
            onAddDraftAttachment = gateway::addDraftAttachment,
            onAddCapturedDraftAttachment = gateway::addCapturedDraftAttachment,
            onRemoveDraftAttachment = gateway::removeDraftAttachment,
            onPreviewDraftImage = gateway::previewDraftImage,
            onPreviewDraftFile = gateway::previewDraftFile,
            onRemoveDraftRef = gateway::removeDraftRef,
            onLoadReferences = gateway::loadReferences, onAddDraftRef = gateway::addDraftRef,
            onRetryPendingInput = gateway::retryPendingInput, onStopRun = gateway::stopRun,
            onReloadModels = gateway::loadModels, onSelectModel = gateway::selectModel,
            onSelectThinking = gateway::selectThinking,
            onLoadQueuedInputs = gateway::loadQueuedInputs,
            onUpdateQueuedInput = gateway::updateQueuedInput,
            onCancelQueuedInput = gateway::cancelQueuedInput,
            onReloadAgents = gateway::loadAgents, onSwitchAgent = gateway::switchAgent,
            onReloadContext = gateway::loadContext,
            onLoadContextPanel = gateway::loadContextPanel,
            onSetContextDirectory = gateway::setContextDirectory,
            onAddContextFile = gateway::addContextFile,
            onCreateContextConversation = gateway::createContextConversation,
            onRefreshConnectionWait = gateway::refreshConnectionWait,
            onRefreshProgress = gateway::refreshProgress,
            onRefreshProgressHome = gateway::refreshProgressHome,
            onProgressHomeAction = gateway::actOnProgressHome,
            onLoadAutomations = gateway::loadAutomations,
            onWorkflowRuns = gateway::workflowRuns,
            onWorkflowDetail = gateway::workflowDetail,
            onCancelWorkflow = gateway::cancelWorkflow,
            onOpenAutomation = gateway::openAutomation,
            onOpenAutomationRun = gateway::openAutomationRun,
            onAutomationAction = gateway::actOnAutomation,
            onCreateAutomation = gateway::createAutomation,
            onUpdateAutomation = gateway::updateAutomation,
            onDeleteAutomation = gateway::deleteAutomation,
            onLoadNotes = gateway::loadNotes,
            onNoteFileSpaces = gateway::noteFileSpaces,
            onNoteFiles = gateway::noteFiles,
            onNoteFileText = gateway::noteFileText,
            onNoteFileContent = gateway::noteFileContent,
            onLoadMoreNotes = gateway::loadMoreNotes,
            onOpenNote = gateway::openNote,
            onNewNote = gateway::beginNoteDraft,
            onNoteDraftChange = gateway::changeNoteDraft,
            onSaveNoteDraft = gateway::saveNoteDraft,
            onCreatedNoteHandled = gateway::noteCreationNavigationHandled,
            onOpenNoteDraft = gateway::openNoteDraft,
            onEditNote = gateway::beginEditNote,
            onResolveNoteConflict = gateway::resolveNoteConflict,
            onNoteMetadataChange = gateway::updateNoteMetadata,
            onLoadNoteHistory = gateway::loadNoteHistory,
            onLoadNoteSnapshot = gateway::loadNoteSnapshot,
            onRestoreNoteSnapshot = gateway::restoreNoteSnapshotToDraft,
            onNoteRestorationHandled = gateway::noteSnapshotRestorationHandled,
            onDeleteNote = gateway::deleteNote,
            onNoteDeletionHandled = gateway::noteDeletionHandled,
            onShareNote = gateway::shareNote,
            onDismissNoteShare = gateway::dismissNoteShare,
            onNoteAiPreview = gateway::previewNoteAi,
            onApplyNoteAi = gateway::applyNoteAi,
            onContinueNoteChat = gateway::openNoteConversation,
            onAttachNoteFile = gateway::attachNoteFile,
            onAttachNoteVoice = gateway::attachNoteVoice,
            onLoadNoteAttachment = gateway::noteAttachmentBytes,
            onLoadShares = gateway::loadShares,
            onCloseShares = gateway::closeShareCenter,
            onRevokeShare = gateway::revokeShare,
            onExtendShare = gateway::extendShare,
            onLoadPersonal = gateway::loadPersonal,
            onLoadPersonalAgent = gateway::loadPersonalAgent,
            onOpenPersonalAgent = gateway::openPersonalAgent,
            onLoadPersonalVoiceChoices = gateway::loadPersonalVoiceChoices,
            onUpdatePersonalAgentProfile = gateway::updatePersonalAgentProfile,
            onLoadPersonalProactivity = gateway::loadPersonalProactivity,
            onSavePersonalProactivity = gateway::savePersonalProactivity,
            onUploadPersonalAvatar = gateway::uploadPersonalAvatar,
            onSavePersonalGoal = gateway::savePersonalGoal,
            onLoadPersonalAssertions = gateway::loadPersonalAssertions,
            onOpenPersonalAssertion = gateway::openPersonalAssertion,
            onClosePersonalAssertion = gateway::closePersonalAssertion,
            onSavePersonalProfile = gateway::savePersonalProfile,
            onSavePersonalStatement = gateway::savePersonalStatement,
            onDeletePersonalAssertion = gateway::deletePersonalAssertion,
            onStartUnderstandingChat = gateway::startUnderstandingChat,
            onOpenGatewayProfiles = gateway::openGatewayProfiles,
            onProbeGateway = gateway::probeGateway,
            onActivateGateway = gateway::activateGateway,
            onRenameGateway = gateway::renameGateway,
            onRemoveGateway = gateway::removeGateway,
            onAutomationRunAction = gateway::actOnAutomationRun,
            onRefreshProgressTasks = gateway::refreshProgressTasks,
            onLoadMoreProgressTasks = gateway::loadMoreProgressTasks,
            onOpenProgressTask = gateway::openProgressTask,
            onProgressTaskCommand = gateway::commandProgressTask,
            onStartProgressTask = gateway::startProgressTask,
            onCreateTaskWithChat = gateway::createTaskWithChat,
            onLoadProgressProjects = gateway::loadProgressProjects,
            onOpenProgressProject = gateway::openProgressProject,
            onCreateProgressTask = gateway::createProgressTask,
            onOpenTaskChat = gateway::openTaskConversation,
            onSaveProgressTask = gateway::saveProgressTask,
            onProgressTaskSearchChange = gateway::changeProgressTaskSearch,
            onSubmitProgressTaskSearch = gateway::submitProgressTaskSearch,
            onOpenExecution = gateway::openExecution, onRetryExecution = gateway::retryExecution,
            onCloseExecution = gateway::closeExecution,
            onSaveMessageAsNote = gateway::saveMessageAsNote,
            onReuseMessage = gateway::reuseMessage,
            onRegenerateMessage = gateway::regenerateMessage,
            onLoadMessageMedia = gateway::readMessageMedia,
            onSpeechChunk = gateway::speechChunk,
            onTranscribeAudio = gateway::transcribeAudio,
            onCreateVoiceCall = gateway::createVoiceCall,
            onCancelVoiceCall = gateway::cancelVoiceCall,
            onVoiceClarification = gateway::respondToVoiceClarification,
            onPendingVoiceApproval = gateway::pendingVoiceApproval,
            onRespondVoiceApproval = gateway::respondToVoiceApproval,
            onAddVoiceAttachment = gateway::addVoiceDraftAttachment,
            onSendVoiceRecording = gateway::sendVoiceRecording,
            onMessageNoteFeedbackHandled = gateway::messageNoteFeedbackHandled,
            modifier = Modifier.safeDrawingPadding())
        }
      },
  )
}
