import { chmodSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { rootCertificates } from 'node:tls';

import { resolveStateDir } from '../config/paths.js';
import type { TunnelRegistration } from './tunnel-types.js';

export function resolveFrpcConfigPath(tunnelId: string): string {
  if (!/^[a-zA-Z0-9_-]+$/.test(tunnelId)) throw new Error('Invalid tunnel id');
  const tmpDir = join(resolveStateDir(), 'tmp');
  mkdirSync(tmpDir, { recursive: true, mode: 0o700 });
  chmodSync(tmpDir, 0o700);
  return join(tmpDir, `frpc-${tunnelId}.toml`);
}

export function removeFrpcConfig(tunnelId: string): void {
  rmSync(resolveFrpcConfigPath(tunnelId), { force: true });
}

// JSON string escapes are also valid TOML basic string escapes.
export function writeFrpcConfig(
  registration: TunnelRegistration,
  localPort: number,
  localHost = '127.0.0.1',
): string {
  const configPath = resolveFrpcConfigPath(registration.tunnelId);
  const caPath = join(resolveStateDir(), 'tmp', 'frp-trusted-roots.pem');
  writeFileSync(caPath, rootCertificates.join('\n'), { mode: 0o600 });
  const { frpc } = registration;
  for (const port of [localPort, frpc.serverPort]) {
    if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('Invalid tunnel port');
  }
  const quote = JSON.stringify;
  const toml = `# Auto-generated by xopc — do not edit
serverAddr = ${quote(frpc.serverAddr)}
serverPort = ${frpc.serverPort}
metadatas.token = ${quote(frpc.authToken)}
loginFailExit = false
transport.tls.enable = true
transport.tls.serverName = ${quote(frpc.serverAddr)}
transport.tls.trustedCaFile = ${quote(caPath)}
transport.heartbeatInterval = 10
transport.heartbeatTimeout = 30

[[proxies]]
name = ${quote(frpc.proxyName)}
type = "http"
localIP = ${quote(localHost)}
localPort = ${localPort}
subdomain = ${quote(frpc.subdomain)}
hostHeaderRewrite = ${quote(new URL(registration.publicUrl).hostname)}
`;
  writeFileSync(configPath, toml, { mode: 0o600 });
  chmodSync(configPath, 0o600);
  return configPath;
}
