import { mkdtempSync, writeFileSync, rmSync, readFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, expect, it, vi } from 'vitest';
import { AgentPluginStore } from '../store.js';
import { savePluginAuthBinding } from '../auth.js';
import { materializePluginServers } from '../mcp-adapter.js';
import { resolveConnectorSecretReferences } from '../../../connectors/secret-store.js';
import { CredentialResolver } from '../../../auth/credentials.js';
import { PLUGIN_SCHEMA, MCP_SCHEMA, pluginServerId } from '../validation.js';

const roots: string[] = [];
const temp = () => { const p = mkdtempSync(join(tmpdir(), 'xopc-plugin-auth-')); roots.push(p); return p; };
afterEach(() => { vi.unstubAllEnvs(); roots.splice(0).forEach(p => rmSync(p, { recursive: true, force: true })); });
it('stores references, resolves only in transport, and detaches credentials when endpoints change', async () => {
  const source = temp(); const state = temp(); const store = new AgentPluginStore(state);
  writeFileSync(join(source, 'plugin.json'), JSON.stringify({ $schema: PLUGIN_SCHEMA, name: 'auth-test' }));
  const mcp = (url: string) => writeFileSync(join(source, 'mcp.json'), JSON.stringify({ $schema: MCP_SCHEMA, mcpServers: { main: { type: 'streamable-http', url } } }));
  mcp('https://one.example/mcp');
  store.install(source, { reviewHash: store.inspect(source).reviewHash });
  await savePluginAuthBinding(store, 'auth-test', 'main', { mode: 'api-key', secrets: [{ target: 'headers', key: 'Authorization', value: 'private-token', prefix: 'Bearer ' }] });
  const materialized = materializePluginServers(store.get('auth-test')!, store)[pluginServerId('auth-test', 'main')];
  expect(JSON.stringify(materialized)).not.toContain('private-token');
  expect(materialized.auth).toBeUndefined();
  expect(await resolveConnectorSecretReferences(materialized, new CredentialResolver({ stateDir: state }))).toMatchObject({ headers: { Authorization: 'Bearer private-token' } });
  const file = readdirSync(join(state, 'plugin-auth/auth-test'))[0];
  expect(readFileSync(join(state, 'plugin-auth/auth-test', file), 'utf8')).not.toContain('private-token');
  mcp('https://two.example/mcp');
  store.install(source, { replace: true, reviewHash: store.inspect(source).reviewHash });
  expect(materializePluginServers(store.get('auth-test')!, store)[pluginServerId('auth-test', 'main')].headers).toBeUndefined();
});
