import { createPrivateKey, createPublicKey, sign } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import {
  browserPairingInvitationPayloadSchema, devicePairingRequestSchema, devicePairingCompleteSchema,
} from '../../../packages/gateway-contract/src/device-pairing.ts';
import { clientRealtimeMessageSchema, serverRealtimeMessageSchema } from '../../../packages/realtime-protocol/src/index.ts';

// Public, deterministic test-only seed. It must never be used as an application identity.
const seed = Buffer.from(Array.from({ length: 32 }, (_, index) => index + 1));
const key = createPrivateKey({ key: Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), seed]), type: 'pkcs8', format: 'der' });
const gatewayPublicKey = createPublicKey(key).export({ format: 'jwk' }).x!;
const signedPayload = Buffer.from(JSON.stringify({ purpose: 'harmony-conformance', text: '中文 🌟' })).toString('base64url');
const fixture = {
  formatVersion: 1,
  note: 'Generated by scripts/export-contracts.mts. JSON Schema omits custom Zod refinements; native rejection tests remain required.',
  schemas: {
    browserPairingInvitation: z.toJSONSchema(browserPairingInvitationPayloadSchema),
    pairingRequest: z.toJSONSchema(devicePairingRequestSchema),
    pairingComplete: z.toJSONSchema(devicePairingCompleteSchema),
    realtimeClient: z.toJSONSchema(clientRealtimeMessageSchema),
    realtimeServer: z.toJSONSchema(serverRealtimeMessageSchema),
  },
  ed25519: { gatewayPublicKey, signedPayload, signature: sign(null, Buffer.from(signedPayload), key).toString('base64url') },
};
const directory = new URL('../fixtures/', import.meta.url);
const destination = new URL('gateway-contract.json', directory);
const output = JSON.stringify(fixture, null, 2) + '\n';
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8') !== output) throw new Error('Harmony contract fixture is stale; run the exporter');
  console.log('Harmony contract fixture is current');
} else {
  await mkdir(directory, { recursive: true }); await writeFile(destination, output);
  console.log('Exported Harmony contract schemas and deterministic signature fixture');
}
