export { resolveXopcDatabasePath, XOPC_DB_FILENAME } from './paths.js';
export {
  XOPC_DB_SCHEMA_VERSION,
  XOPC_DB_BASELINE_SCHEMA_VERSION,
  SCHEMA_META_SCHEMA_VERSION_KEY,
  ensureXopcDatabaseSchema,
  readSchemaVersionForTest,
  readSchemaVersion,
} from './schema.js';
export {
  applyPendingMigrations,
  inspectSchemaMigrationStatus,
  resolveMigrationsDir,
  type SchemaMigrationStatus,
} from './migrations/runner.js';
export {
  DatabaseSchemaMigrationGapError,
  DatabaseSchemaTooNewError,
} from './migrations/errors.js';
export { discoverSqlMigrations, listRegisteredMigrationTargets } from './migrations/discover.js';
export {
  closeXopcDatabase,
  getXopcDatabase,
  isXopcDatabaseOpen,
  openXopcDatabase,
  requireXopcDatabase,
  resetXopcDatabaseSingletonForTest,
  type OpenXopcDatabaseOptions,
  type XopcDatabase,
} from './connection.js';
export { getSqliteDatabase, runSqliteWriteTransaction } from './transaction.js';
export {
  claimContextExtractionRun,
  finishContextExtractionRun,
  getContextExtractionRun,
  hasIndependentExtractionOutput,
  listContextExtractionOutputs,
  listContextExtractionRuns,
  type ContextExtractionOutput,
  type ContextExtractionRun,
  type ContextExtractionStatus,
  type ContextObjectType,
} from './context-extraction-repository.js';
export {
  closeTemporalAssertions,
  createTemporalAssertion,
  linkContextObjects,
  listContextObjectRelations,
  listTemporalAssertions,
  type ContextObjectRelation,
  type ContextTemporalAssertion,
} from './context-relation-repository.js';
export {
  finishContextConsolidationRun,
  getContextConsolidationRun,
  listContextConsolidationDecisions,
  listContextConsolidationRuns,
  recordContextConsolidationDecision,
  startContextConsolidationRun,
  type ContextConsolidationDecision,
  type ContextConsolidationRun,
} from './context-consolidation-repository.js';
export {
  summarizeUnderstandingFeedback,
  summarizeUserUnderstandingQuality,
  type UnderstandingFeedbackSummary,
  type UserUnderstandingQualityMetrics,
} from './user-context-quality-repository.js';
export {
  createCollaborationRule,
  createContextEvidence,
  createUnderstanding,
  closeUnderstandingValidity,
  consumeContextConsent,
  deleteCollaborationRule,
  deleteUnderstanding,
  decideContextConsent,
  ensureContextConsent,
  getCollaborationRule,
  getTurnPersonalization,
  getUnderstanding,
  getUserProfile,
  hasContextConsent,
  isUnderstandingSuppressed,
  listCollaborationRules,
  listUnderstandingEvidence,
  listUnderstandingStatusEvents,
  listUnderstandings,
  linkUnderstandingEvidence,
  recordContextFeedback,
  recordContextRun,
  rejectUnderstanding,
  reviseCollaborationRule,
  reviseUnderstanding,
  searchActiveUnderstandings,
  setCollaborationRuleStatus,
  setUnderstandingStatus,
  updateUserProfile,
  type CreateUnderstandingInput,
  type UnderstandingStatusEvent,
} from './user-context-repository.js';
export {
  getUserPerson,
  getUserPeopleIndexState,
  listUserPeople,
  mergeUserPeople,
  replaceUserPeopleIndex,
  summarizeUserPeople,
  updateUserPerson,
} from './user-people-repository.js';
export {
  cancelQueuedSessionInput,
  claimNextSessionInput,
  findSessionInput,
  finishSessionInputRun,
  getSessionInputState,
  getSessionInputById,
  insertSessionInput,
  listActiveSessionInputRuns,
  mutateQueuedSessionInput,
  recoverSessionInputState,
  setSessionInputStatus,
  type SessionInput,
  type SessionInputDelivery,
  type SessionInputState,
  type SessionInputStatus,
} from './session-input-repository.js';
export {
  replaceLatestSessionTurnAndQueueInput,
  validateLatestSessionTurnTarget,
  type ReplaceLatestSessionTurnInput,
  type ReplaceLatestSessionTurnResult,
} from './session-turn-replace-repository.js';
export {
  acknowledgeHomeAttention,
  isHomeAttentionAcknowledged,
  type HomeAttentionSubjectKind,
} from './home-attention-repository.js';
export {
  claimNextConnectorLearningJob,
  enqueueConnectorLearningJob,
  listConnectorLearningJobs,
  recoverStaleConnectorLearningJobs,
  setConnectorLearningPaused,
  updateConnectorLearningJob,
  type ConnectorLearningJob,
  type ConnectorLearningMode,
  type ConnectorLearningPhase,
  type ConnectorLearningStatus,
} from './connector-learning-repository.js';
export {
  appendComposerInputHistory,
  clearComposerInputHistory,
  listComposerInputHistory,
  COMPOSER_INPUT_HISTORY_LIMIT,
  type ComposerInputHistoryItem,
} from './composer-input-history-repository.js';
export {
  bindEndpointPrincipal,
  createEndpointPrincipal,
  getEndpointPrincipal,
  listEndpointPrincipals,
  revokeEndpointPrincipal,
  touchEndpointPrincipal,
  type EndpointPrincipal,
} from './endpoint-principal-repository.js';
export {
  finishEndpointToolInvocationAudit,
  listEndpointToolInvocationAudits,
  startEndpointToolInvocationAudit,
  type EndpointToolInvocationAudit,
} from './endpoint-tool-invocation-repository.js';
export {
  getInteractionState,
  setInteractionState,
  updateInteractionStateFromMessage,
  type InteractionState,
} from './interaction-state-repository.js';
export {
  getSessionTaskPlan,
  setSessionTaskPlan,
  type SessionTaskPlan,
  type SessionTaskPlanItem,
  type SessionTaskPlanItemStatus,
} from './session-task-plan-repository.js';
export {
  buildRelationshipPrompt,
  getRelationshipSettings,
  isProactiveSupportAllowed,
  updateRelationshipSettings,
  type RelationshipSettings,
  type SupportMode,
} from './relationship-settings-repository.js';
export {
  buildDefaultSessionMetadata,
  type SessionMetadataSeed,
} from './session-metadata.js';
export {
  buildGlobalSessionStats,
  classifyStoredRow,
  estimateTokensFromMessages,
  extractFtsContent,
  metadataToSessionInsert,
  sessionConfigRowToConfig,
  sessionRowToMetadata,
  transcriptEntryRowToStoredRow,
  type SessionConfigRow,
  type SessionRow,
  type TranscriptEntryRow,
} from './row-mappers.js';
export {
  deleteSessionRecord,
  ensureSessionRecord,
  getCurrentSessionId,
  getGlobalSessionStats,
  findSessionKeyBySessionId,
  getSessionPersistedLevels,
  getSessionMetadata,
  incrementSessionStatsOnAppend,
  listSessionMetadata,
  listSessionsByAgent,
  patchSessionMetadata,
  resetSessionRecord,
  resolveSessionAgentId,
  updateSessionStats,
} from './session-repository.js';
export {
  appendCompactionBoundaryIfUnchanged,
  appendTranscriptEntry,
  listCompactionBoundaries,
  loadLlmMessagesForSession,
  loadTranscriptHistoryRowsForSession,
  loadTranscriptRows,
  loadTranscriptRowsForSession,
  loadCompactionSourceSnapshot,
  paginateTranscriptMessages,
  replaceTranscriptRows,
  restoreBeforeCompactionBoundary,
  searchSessionTranscript,
  type CompactionSourceSnapshot,
  type SessionTranscriptRecallMatch,
  type TranscriptSourceEntry,
} from './transcript-repository.js';
export {
  deleteNoteRecord,
  getNoteRecord,
  listNoteRecords,
  upsertNoteRecord,
} from './notes-repository.js';
export {
  deleteNoteAgentContextRecord,
  getNoteAgentContextRecord,
  upsertNoteAgentContextRecord,
  type NoteAgentContextRecord,
} from './note-agent-context-repository.js';
export {
  appendMemorySignal,
  appendMemoryTraceEvent,
  countMemoryRecordsBySourceInstanceId,
  deleteMemoryRecordsBySourceInstanceId,
  deleteMemoryRecord,
  getMemoryProviderState,
  getMemoryTurnFeedback,
  getMemoryRecord,
  hasUnresolvedMemoryConflict,
  listMemorySignals,
  listMemoryTraceEvents,
  listMemoryRecords,
  markMemoryRecordsConflicted,
  searchMemoryRecords,
  setMemoryRecordStatus,
  setMemoryProviderState,
  setMemoryTurnFeedback,
  summarizeMemoryRecallFeedback,
  upsertMemoryRecord,
  type AppendMemorySignalInput,
  type AppendMemoryTraceEventInput,
  type ListMemoryRecordsOptions,
  type MemoryRecallFeedbackSummary,
  type MemorySignalRowPayload,
  type MemoryFeedback,
  type MemoryFeedbackRating,
  type MemoryTraceEventPayload,
  type SearchMemoryRecordsOptions,
  type SetMemoryTurnFeedbackInput,
  type UpsertMemoryRecordInput,
} from './memory-records-repository.js';
export {
  attachMemoryEvidence,
  claimKnowledgeSourceItems,
  countKnowledgeSourceItems,
  completeKnowledgeSourceItemSynthesis,
  deleteMemoryEvidenceForRecord,
  deleteKnowledgeSourceItems,
  finishKnowledgeSyncRun,
  getKnowledgeConsumerWatermark,
  getKnowledgeSourceCursor,
  getKnowledgeSourceItem,
  listKnowledgeSourceItems,
  listKnowledgeSourceChanges,
  listKnowledgeSyncRuns,
  listMemoryEvidence,
  pruneBoundedKnowledgeSourceItems,
  setKnowledgeSourceItemSynthesisStatus,
  setKnowledgeConsumerWatermark,
  setKnowledgeSourceCursor,
  startKnowledgeSyncRun,
  upsertKnowledgeSourceItems,
} from './knowledge-repository.js';
export {
  deleteSessionConfig,
  getSessionConfig,
  hasSessionConfig,
  setSessionConfig,
  updateSessionConfig,
} from './config-repository.js';
export {
  createObjectLinkRecord,
  deleteObjectLinkRecord,
  getActivityEventRecord,
  listActivityRecords,
  listObjectActivityRecords,
  listObjectLinkRecords,
  listProjectActivityRecords,
  recordActivityEvent,
} from './activity-repository.js';
export {
  appendConnectorExecutionAudit,
  claimConnectorWebhookDelivery,
  completeConnectorWebhookDelivery,
  consumeConnectorApproval,
  createConnectorApproval,
  decideConnectorApproval,
  deleteConnectorConnection,
  deleteConnectorInstallation,
  getConnectorConnection,
  getConnectorApproval,
  getConnectorInstallation,
  getCachedConnectorCatalogEntry,
  listCachedConnectorCatalogEntries,
  listConnectorActionMetadata,
  listConnectorApprovals,
  listConnectorConnections,
  listConnectorExecutionAudit,
  listConnectorInstallations,
  releaseConnectorWebhookDelivery,
  replaceConnectorCatalogEntries,
  upsertConnectorActionMetadata,
  upsertConnectorCatalogEntry,
  upsertConnectorConnection,
  upsertConnectorInstallation,
  type CachedConnectorCatalogEntry,
} from './connector-repository.js';
export {
  getConnectorAccount,
  listConnectorAccounts,
  refreshConnectorAccountCurrent,
  reconcileConnectorAccount,
} from './connector-account-repository.js';
export {
  getConnectorSyncPolicy,
  getConnectorSyncPolicyForConnection,
  listConnectorSyncPolicies,
  upsertConnectorSyncPolicy,
  type ConnectorSyncPolicy,
} from './connector-sync-policy-repository.js';
export {
  getUserTrustPolicy,
  setUserTrustPolicy,
} from './user-trust-repository.js';
