import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Cloud,
  Cpu,
  FileText,
  FolderOpen,
  Globe,
  Heart,
  Zap,
  Radio,
  Image as ImageIcon,
  Keyboard,
  KeyRound,
  Layers,
  MessageSquare,
  Mic,
  Moon,
  Package,
  Palette,
  PawPrint,
  Plug,
  Search,
  Share2,
  Shield,
  Target,
  UserCircle,
  Users,
} from 'lucide-react';

import type { Tab } from '@/i18n/messages';

const TAB_ICONS: Record<Tab, LucideIcon> = {
  chat: MessageSquare,
  sessions: FolderOpen,
  automations: Zap,
  skills: Layers,
  connectors: Plug,
  goals: Target,
  channels: Plug,
  agents: Users,
  logs: FileText,
  settingsOverview: Activity,
  settingsCredentials: KeyRound,
  settingsAppearance: Palette,
  settingsKeyboardShortcuts: Keyboard,
  settingsSystem: Shield,
  settingsDesktopPet: PawPrint,
  settingsDesktopApp: Package,
  settingsAgentBrowser: Globe,
  settingsUserProfile: UserCircle,
  settingsCapabilityPresets: Layers,
  settingsAgents: Users,
  settingsProviders: Cloud,
  settingsModels: Cpu,
  settingsImageModels: ImageIcon,
  settingsChannels: Plug,
  settingsVoice: Mic,
  settingsGateway: Globe,
  settingsHeartbeat: Heart,
  settingsTunnel: Radio,
  settingsSearch: Search,
  settingsShares: Share2,
  settingsDreams: Moon,
  settingsGoals: Target,
};

export function TabIcon({ tab, className }: { tab: Tab; className?: string }) {
  const Icon = TAB_ICONS[tab];
  return <Icon className={className} strokeWidth={1.75} aria-hidden />;
}
