import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { canonicalJson, deviceStateDescriptor, locationDescriptor } from '../../packages/endpoint-tools-protocol/src/index.js';

const descriptors = ['state', 'power'].map(capability => deviceStateDescriptor('mobile', capability as 'state' | 'power'));
const stateCatalog = canonicalJson(descriptors);
descriptors.push(locationDescriptor('mobile'));
const catalog = canonicalJson(descriptors);
const revisions = descriptors.map(descriptor => createHash('sha256').update(canonicalJson(descriptor)).digest('hex'));
const outputs: Record<string, string> = {
  'apps/mobile-android/app/src/main/java/ai/xopc/mobile/gateway/DeviceToolCatalog.kt': `// Generated by scripts/devices/generate-mobile-tools.mts.\npackage ai.xopc.mobile.gateway\n\ninternal object DeviceToolCatalog {\n  const val stateJson = """${stateCatalog}"""\n  const val json = """${catalog}"""\n  val revisions = listOf(${revisions.map(value => JSON.stringify(value)).join(', ')})\n}\n`,
  'apps/mobile-harmony/entry/src/main/ets/common/deviceToolCatalog.ets': `// Generated by scripts/devices/generate-mobile-tools.mts.\nexport const DEVICE_STATE_TOOL_CATALOG_JSON: string = ${JSON.stringify(stateCatalog)};\nexport const DEVICE_TOOL_CATALOG_JSON: string = ${JSON.stringify(catalog)};\nexport const DEVICE_TOOL_REVISIONS: string[] = ${JSON.stringify(revisions)};\n`,
  'apps/mobile-ios/XopcMobile/Core/Networking/DeviceToolCatalog.swift': `// Generated by scripts/devices/generate-mobile-tools.mts.\nimport Foundation\n\nenum DeviceToolCatalog {\n    static let stateJson = #"${stateCatalog}"#\n    static let json = #"${catalog}"#\n    static let revisions = [${revisions.map(value => JSON.stringify(value)).join(', ')}]\n}\n`,
};
for (const [path, content] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Stale generated device catalog: ${path}`);
  } else writeFileSync(path, content);
}
