import type { ProactivePreferences } from '@xopcai/gateway-contract';
import useSWR from 'swr';

import { Select, SelectOption } from '@/components/ui/popover-select';
import { Skeleton } from '@/components/ui/skeleton';
import { proactiveGet } from './api';

const inputClass = 'mt-1 w-full rounded-lg border border-edge bg-surface-panel px-3 py-2 text-sm text-fg';
export function DeliverySettings({ value, onChange, zh }: { value: ProactivePreferences; onChange: (value: ProactivePreferences) => void; zh: boolean }) {
  const channels = zh ? { all: '所有已启用设备', auto: '自动选择一台设备', browser: '浏览器 / 桌面', mobile: '手机', telegram: 'Telegram' } : { all: 'All enabled devices', auto: 'Choose one device', browser: 'Browser / desktop', mobile: 'Mobile', telegram: 'Telegram' };
  return <div className="space-y-4 border-t border-edge pt-4">
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.digestEnabled} onChange={(event) => onChange({ ...value, digestEnabled: event.target.checked })} />{zh ? '将提醒合并为每日摘要' : 'Combine alerts into a daily digest'}</label>
    <label className="block text-sm">{zh ? '摘要时间（使用上方时区）' : 'Digest time (in your selected timezone)'}<input className={inputClass} type="time" required value={`${String(value.digestHour).padStart(2, '0')}:${String(value.digestMinute).padStart(2, '0')}`} onChange={(event) => { const [hour, minute] = event.target.value.split(':').map(Number); onChange({ ...value, digestHour: hour, digestMinute: minute }); }} /></label>
    <label className="block text-sm">{zh ? '提醒渠道' : 'Notification channel'}<Select value={value.preferredChannel} onChange={(event) => onChange({ ...value, preferredChannel: event.target.value as ProactivePreferences['preferredChannel'] })}>{Object.entries(channels).map(([id, label]) => <SelectOption key={id} value={id}>{label}</SelectOption>)}</Select></label>
    <p className="text-xs text-fg-muted">{zh ? '自动选择优先使用最近注册的浏览器，否则选择一台手机。免打扰期间的重要提醒会合并为一份摘要。' : 'Automatic selection prefers the most recently registered browser, then one mobile device. Important alerts during quiet hours are combined into one digest.'}</p>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.suppressWhileViewing} onChange={(event) => onChange({ ...value, suppressWhileViewing: event.target.checked })} />{zh ? '正在查看卡片时不再发送系统提醒' : 'Skip system alerts while viewing cards'}</label>
    {value.preferredChannel === 'telegram' && <fieldset className="space-y-3 rounded-xl border border-edge p-3"><legend className="px-1 text-sm">Telegram</legend>{(['chatId', 'accountId', 'publicUrl'] as const).map((field) => <label key={field} className="block text-sm">{field === 'chatId' ? (zh ? '接收对话 ID' : 'Destination chat ID') : field === 'accountId' ? (zh ? '账号 ID（可选）' : 'Account ID (optional)') : (zh ? '可从外部访问的控制台 HTTPS 地址' : 'Public HTTPS console URL')}<input className={inputClass} required={field !== 'accountId'} value={value.telegram?.[field] ?? ''} onChange={(event) => onChange({ ...value, telegram: { chatId: value.telegram?.chatId ?? '', publicUrl: value.telegram?.publicUrl ?? '', ...(value.telegram?.accountId ? { accountId: value.telegram.accountId } : {}), [field]: field === 'accountId' ? event.target.value || undefined : event.target.value } })} /></label>)}<p className="text-xs text-fg-muted">{zh ? '需要已连接 Telegram 渠道。发送通用摘要和卡片链接；链接中不要填写访问令牌。' : 'Connect the Telegram channel first. Alerts contain a generic summary and a card link. Do not put access tokens in the URL.'}</p></fieldset>}
  </div>;
}

export function ProactiveStatistics({ zh }: { zh: boolean }) {
  const { data, isLoading, error } = useSWR<{ metrics: { usage: { inputTokens: number | null; outputTokens: number | null; estimatedCostUsd: number | null; pricedRuns: number; totalRuns: number }; cards: { total: number; resolved: number; withdrawn: number }; feedback: Array<{ rating: string; count: number }>; interruptions: Array<{ day: string; count: number }>; browser: Array<{ status: string; count: number }>; telegram: Array<{ status: string; count: number }> } }>('/api/proactive/metrics', proactiveGet, { refreshInterval: 30000 });
  if (isLoading) return <Skeleton className="h-40 max-w-2xl rounded-2xl" />;
  if (error) return <p role="alert" className="text-danger">{String(error)}</p>;
  const metrics = data?.metrics;
  if (!metrics) return null;
  const useful = metrics.feedback.find((item) => item.rating === 'useful')?.count ?? 0;
  const totalFeedback = metrics.feedback.reduce((sum, item) => sum + item.count, 0);
  return <section className="max-w-2xl space-y-3 rounded-2xl border border-edge bg-surface-panel p-5"><h2 className="font-medium">{zh ? '最近 30 天' : 'Last 30 days'}</h2><div className="grid grid-cols-3 gap-3 text-sm"><p>{zh ? '卡片' : 'Cards'}<strong className="block text-xl">{metrics.cards.total}</strong></p><p>{zh ? '已处理' : 'Resolved'}<strong className="block text-xl">{metrics.cards.resolved ?? 0}</strong></p><p>{zh ? '有用率' : 'Useful feedback'}<strong className="block text-xl">{totalFeedback ? `${Math.round(useful / totalFeedback * 100)}%` : '—'}</strong></p></div><p className="text-xs text-fg-muted">{zh ? '有用率仅统计已反馈卡片。费用为模型返回用量与价格表估算，不代表实际账单。投递接受不等于用户看到通知。' : 'Usefulness measures submitted feedback. Cost uses reported usage and model pricing, not billing data. Provider acceptance does not prove a notification was seen.'}</p><p className="text-xs text-fg-muted">Tokens: {metrics.usage.inputTokens ?? '—'} / {metrics.usage.outputTokens ?? '—'} · {zh ? '已知成本估算' : 'Known cost estimate'}: {metrics.usage.estimatedCostUsd == null ? '—' : `$${metrics.usage.estimatedCostUsd.toFixed(4)}`} ({metrics.usage.pricedRuns}/{metrics.usage.totalRuns})</p><details className="text-sm"><summary className="cursor-pointer">{zh ? '通知与投递记录' : 'Notification and delivery counts'}</summary><ul className="mt-3 space-y-1">{metrics.interruptions.slice(0, 7).map((item) => <li key={item.day}>{item.day} · {item.count} {zh ? '次提醒' : 'alerts'}</li>)}{[...metrics.browser.map((item) => ({ ...item, channel: 'Web Push' })), ...metrics.telegram.map((item) => ({ ...item, channel: 'Telegram' }))].map((item) => <li key={`${item.channel}:${item.status}`}>{item.channel} · {item.status} · {item.count}</li>)}</ul></details></section>;
}
