export function taskCopy(language: 'en' | 'zh') {
  return language === 'zh' ? {
    newWork: '交给 xopc',
    dialogTitle: '现在想完成什么？',
    dialogDescription: '发送后会建立一个持续推进的结果。xopc 会理解目标、执行、验证，并在真正需要你时再提问。',
    intentLabel: '告诉 xopc 你要做什么',
    intentPlaceholder: '例如：整理这周的会议记录，提炼待办并给出下周优先级',
    submit: '进入对话并开始',
    starting: '正在开始…',
    projectLabel: '归属项目',
    monitoringLabel: '主动跟进',
    monitoringModes: {
      observe: '仅观察',
      ask_before_action: '行动前询问',
      auto_low_risk: '自动执行低风险操作',
    },
    existingProject: '已有项目',
    newProject: '新项目',
    needsAttention: '需要你处理',
    waitingStatus: '当前等待',
    runAttention: '运行异常',
    running: 'xopc 正在处理',
    continue: '继续推进',
    recent: '最近对话',
    recentTasks: '最近完成',
    evidenceCount: '项证据',
    remainingCount: '项待继续',
    projects: '长期项目',
    emptyRunning: '当前没有正在处理的对话',
    emptyContinue: '还没有需要继续推进的事项',
    openChat: '打开对话',
    whyNow: '为什么现在',
    impact: '影响',
    workDone: 'AI 已完成',
    recommendation: '建议',
    judgmentReasons: '判断依据',
    rejectedAlternatives: '未选方案',
    uncertainty: '不确定性',
    snooze: '明天再看',
    dismiss: '忽略',
    feedbackPlaceholder: '告诉 AI：以后遇到这类情况应该怎样判断…',
    applyFeedback: '调整后续判断',
    taskStatuses: {
      pending: '待推进',
      planning: '正在明确完成标准',
      waiting_dependency: '等待前置任务',
      running: '正在推进',
      verifying: '正在验证',
      needs_user: '需要你',
      blocked: '已阻塞',
      paused: '已暂停',
      completed: '已完成',
      cancelled: '已结束',
    },
    taskProgress: {
      title: 'xopc 已接手',
      open: '查看结果',
      decide: '查看并决定',
      evidence: '项已验证依据',
      statuses: {
        pending: '待推进',
        planning: '正在明确完成标准',
        waiting_dependency: '等待前置任务',
        running: '正在推进',
        verifying: '正在验证',
        needs_user: '需要你',
        blocked: '已阻塞',
        paused: '已暂停',
        completed: '已完成',
        cancelled: '已结束',
      },
    },
    successDefinition: '怎样才算完成',
    attachments: '任务附件',
    currentPlan: '当前推进计划',
    currentStep: '当前步骤',
    nextCheck: '下次主动检查',
    taskRelations: '任务关系',
    dependencies: '前置任务',
    dependents: '后续任务',
    noDependencies: '没有前置任务',
    noDependents: '没有后续任务',
    editDependencies: '编辑前置任务',
    saveDependencies: '保存关系',
    cancelDependencyEdit: '取消',
    dependenciesDescription: '所选任务全部完成后，xopc 才会开始推进当前任务。',
    linkDependencies: '关联前置任务',
    linkedDependencies: '已关联 {{count}} 个前置任务',
    dependencySearchPlaceholder: '搜索任务名称',
    noDependencyMatches: '没有匹配的任务',
    noDependencyCandidates: '没有可选的其他任务',
    removeDependency: '移除前置任务：{{task}}',
    dependencyUpdateFailed: '前置任务更新失败，请刷新后重试。',
    expectedOutputs: '预期输出',
    constraints: '约束与边界',
    approvalRequired: '需要你批准',
    executionReceipts: '执行回执',
    latestResult: '最新结果',
    remainingWork: '还差什么',
    nextAction: '下一步',
    yourDecision: '只需你决定',
    noRemainingWork: '已覆盖全部完成标准。',
    noDecisionNeeded: '暂时不需要你做任何事，xopc 会继续推进。',
    evidenceDetails: '查看依据',
    contextUsed: '本次使用的上下文',
    contextSources: '信息来源',
    contextAssumptions: '当前假设',
    unresolvedCriteria: '待验证标准',
    resultFeedback: '这件事做好了吗？',
    doneWell: '做好了',
    needsFix: '没做好',
    correctionPlaceholder: '告诉 xopc 哪里不对、你真正想要的结果是什么',
    submitCorrection: '修正并继续',
    feedbackThanks: '收到，我会据此继续改进。',
    correctionStarted: '收到，已重新打开并开始修正。',
    noDefinition: '系统正在进一步明确完成标准。未明确前不会把事情误判为已完成。',
    noReceipts: '还没有执行回执。',
    backToWork: '返回首页',
    openTaskConversation: '进入对话',
    taskNotFound: '没有找到这个任务',
    runTask: '开始推进',
    pauseTask: '暂时暂停',
    resumeTask: '继续推进',
    cancelTask: '结束事项',
    actionFailed: '操作失败，请重试。',
    verificationStatuses: {
      passed: '已验证',
      failed: '验证未通过',
      unverified: '待验证',
    },
  } : {
    newWork: 'Ask xopc',
    dialogTitle: 'What do you want to get done?',
    dialogDescription: 'This creates a durable task. xopc will understand it, execute, verify, and ask only when your input is truly needed.',
    intentLabel: 'Tell xopc what you need',
    intentPlaceholder: 'For example: summarize this week’s meeting notes and suggest next week’s priorities',
    submit: 'Open conversation and start',
    starting: 'Starting…',
    projectLabel: 'Project',
    monitoringLabel: 'Proactive follow-up',
    monitoringModes: {
      observe: 'Observe only',
      ask_before_action: 'Ask before acting',
      auto_low_risk: 'Auto-run low-risk actions',
    },
    existingProject: 'Existing project',
    newProject: 'New project',
    needsAttention: 'Needs your attention',
    waitingStatus: 'Current status',
    runAttention: 'Run issues',
    running: 'xopc is working',
    continue: 'Continue',
    recent: 'Recent conversations',
    recentTasks: 'Recent tasks',
    evidenceCount: 'evidence items',
    remainingCount: 'remaining',
    projects: 'Long-term projects',
    emptyRunning: 'No conversations are running',
    emptyContinue: 'No ongoing items yet',
    openChat: 'Open conversation',
    whyNow: 'Why now',
    impact: 'Impact',
    workDone: 'AI checked',
    recommendation: 'Recommendation',
    judgmentReasons: 'Why this is recommended',
    rejectedAlternatives: 'Alternatives not chosen',
    uncertainty: 'Uncertainty',
    snooze: 'Tomorrow',
    dismiss: 'Dismiss',
    feedbackPlaceholder: 'Tell AI how to judge this kind of event next time…',
    applyFeedback: 'Update future judgments',
    taskStatuses: {
      pending: 'Pending',
      planning: 'Defining done',
      waiting_dependency: 'Waiting on dependencies',
      running: 'In progress',
      verifying: 'Verifying',
      needs_user: 'Needs you',
      blocked: 'Blocked',
      paused: 'Paused',
      completed: 'Completed',
      cancelled: 'Ended',
    },
    taskProgress: {
      title: 'xopc owns this task',
      open: 'View task',
      decide: 'Review and decide',
      evidence: 'verified evidence',
      statuses: {
        pending: 'Pending',
        planning: 'Defining done',
        waiting_dependency: 'Waiting on dependencies',
        running: 'In progress',
        verifying: 'Verifying',
        needs_user: 'Needs you',
        blocked: 'Needs you',
        paused: 'Paused',
        completed: 'Completed',
        cancelled: 'Ended',
      },
    },
    successDefinition: 'Definition of done',
    attachments: 'Task attachments',
    currentPlan: 'Current plan',
    currentStep: 'Current step',
    nextCheck: 'Next proactive check',
    taskRelations: 'Task relationships',
    dependencies: 'Dependencies',
    dependents: 'Dependent tasks',
    noDependencies: 'No dependencies',
    noDependents: 'No dependent tasks',
    editDependencies: 'Edit dependencies',
    saveDependencies: 'Save relationships',
    cancelDependencyEdit: 'Cancel',
    dependenciesDescription: 'xopc starts this task after every selected task is complete.',
    linkDependencies: 'Link dependencies',
    linkedDependencies: 'Linked dependencies: {{count}}',
    dependencySearchPlaceholder: 'Search tasks',
    noDependencyMatches: 'No matching tasks',
    noDependencyCandidates: 'There are no other tasks to select',
    removeDependency: 'Remove dependency: {{task}}',
    dependencyUpdateFailed: 'Dependencies could not be updated. Refresh and try again.',
    expectedOutputs: 'Expected outputs',
    constraints: 'Constraints and boundaries',
    approvalRequired: 'Your approval is required',
    executionReceipts: 'Execution receipts',
    latestResult: 'Latest result',
    remainingWork: 'What remains',
    nextAction: 'Next action',
    yourDecision: 'Your one decision',
    noRemainingWork: 'All completion criteria are covered.',
    noDecisionNeeded: 'Nothing is needed from you. xopc will keep moving this forward.',
    evidenceDetails: 'View evidence',
    contextUsed: 'Context used for this task',
    contextSources: 'Sources',
    contextAssumptions: 'Current assumptions',
    unresolvedCriteria: 'Criteria still to verify',
    resultFeedback: 'Was this done well?',
    doneWell: 'Yes, done',
    needsFix: 'Needs fixing',
    correctionPlaceholder: 'Tell xopc what is wrong and what the right task should be',
    submitCorrection: 'Fix and continue',
    feedbackThanks: 'Got it. I will use this to improve future work.',
    correctionStarted: 'Got it. This was reopened and correction has started.',
    noDefinition: 'xopc is still clarifying the completion criteria. It will not mark this done before they are explicit.',
    noReceipts: 'No execution receipts yet.',
    backToWork: 'Back to home',
    openTaskConversation: 'Open conversation',
    taskNotFound: 'This task was not found',
    runTask: 'Start working',
    pauseTask: 'Pause',
    resumeTask: 'Continue',
    cancelTask: 'End task',
    actionFailed: 'The action failed. Please try again.',
    verificationStatuses: {
      passed: 'Verified',
      failed: 'Verification failed',
      unverified: 'Not verified',
    },
  };
}
