export function taskCopy(language: 'en' | 'zh') {
  return language === 'zh' ? {
    newWork: '交给 xopc',
    dialogTitle: '现在想完成什么？',
    dialogDescription: '发送后会进入新对话。xopc 会直接回答或开始处理；需要持续推进时，再转为任务。',
    intentLabel: '告诉 xopc 你要做什么',
    intentPlaceholder: '例如：整理这周的会议记录，提炼待办并给出下周优先级',
    intentSuggestion: '整理这周的会议记录，提炼待办并给出下周优先级',
    submit: '进入对话并开始',
    projectLabel: '归属项目',
    monitoringLabel: '主动跟进',
    monitoringModes: {
      observe: '仅观察',
      ask_before_action: '行动前询问',
      auto_low_risk: '自动执行低风险操作',
    },
    existingProject: '已有项目',
    newProject: '新项目',
    needsAttention: '需要你处理',
    waitingStatus: '当前等待',
    runAttention: '运行异常',
    running: 'xopc 正在处理',
    continue: '继续推进',
    recent: '最近对话',
    evidenceCount: '项证据',
    remainingCount: '项待继续',
    projects: '长期项目',
    emptyRunning: '当前没有正在处理的对话',
    emptyContinue: '还没有需要继续推进的事项',
    openChat: '打开对话',
    whyNow: '为什么现在',
    impact: '影响',
    workDone: 'AI 已完成',
    recommendation: '建议',
    policyReason: '处理依据',
    proposedAction: '拟执行动作',
    actionStates: {
      not_authorized: '仅建议，未获自动执行授权',
      approval_required: '等待你批准',
      pending: '等待执行',
      executing: '正在执行',
      completed: '已自动执行',
      rejected: '已拒绝',
      failed: '执行失败',
    },
    judgmentReasons: '判断依据',
    rejectedAlternatives: '未选方案',
    uncertainty: '不确定性',
    snooze: '明天再看',
    dismiss: '忽略',
    feedbackPlaceholder: '告诉 AI：以后遇到这类情况应该怎样判断…',
    applyFeedback: '调整后续判断',
    taskStatuses: {
      pending: '待推进',
      planning: '正在明确完成标准',
      waiting_dependency: '等待前置任务',
      running: '正在推进',
      verifying: '正在验证',
      needs_user: '需要你',
      blocked: '已阻塞',
      paused: '已暂停',
      completed: '已完成',
      cancelled: '已结束',
    },
    taskProgress: {
      title: 'xopc 已接手',
      open: '查看结果',
      decide: '查看并决定',
      evidence: '项已验证依据',
      statuses: {
        pending: '待推进',
        planning: '正在明确完成标准',
        waiting_dependency: '等待前置任务',
        running: '正在推进',
        verifying: '正在验证',
        needs_user: '需要你',
        blocked: '已阻塞',
        paused: '已暂停',
        completed: '已完成',
        cancelled: '已结束',
      },
    },
    detailStatuses: {
      captured: '尚未安排',
      ready: '等待开始',
      queued: '已进入队列',
      running: '正在执行',
      verifying: '正在验证',
      waiting: '等待条件',
      blocked: '被阻塞',
      needsUser: '需要你处理',
      review: '等待验收',
      completed: '已完成',
      ended: '已结束',
      paused: '待继续',
    },
    detailStatusDescriptions: {
      captured: '任务已记录，但尚未进入执行队列。安排后，xopc 会开始推进。',
      ready: '任务已经准备好，可以交给 xopc 开始执行。',
      queued: '任务已进入执行队列，xopc 将在资源可用时开始。',
      running: 'xopc 正在推进这个任务。',
      verifying: 'xopc 正在根据完成标准核验结果。',
      waiting: '任务正在等待外部条件满足。',
      blocked: '当前存在阻塞条件，解除后才能继续。',
      needsUser: 'xopc 需要你的输入或批准后才能继续。',
      review: '执行结果已经准备好，等待你验收。',
      completed: '任务已经完成并关闭。',
      ended: '任务已经结束，不会继续执行。',
      paused: '任务目前没有运行，可以随时继续。',
    },
    statusSummary: '当前状态',
    taskLabel: '任务',
    taskDescription: '任务描述与目标',
    editTaskField: '编辑',
    saveTaskField: '保存',
    cancelTaskField: '取消',
    noTaskDescription: '添加任务背景、范围和交付要求。',
    taskProperties: '任务属性',
    taskPhase: '阶段',
    priority: '优先级',
    dueDate: '截止日期',
    executorLabel: '执行 Agent',
    priorityLabels: { low: '低优先级', normal: '普通优先级', high: '高优先级', critical: '紧急' },
    unassigned: '未指定执行者',
    noDueDate: '无截止时间',
    updatedAt: '更新于 {{date}}',
    successDefinition: '怎样才算完成',
    taskDefinition: '任务定义',
    criteriaProgress: '{{verified}}/{{total}} 已验证',
    taskRelations: '任务关系',
    dependencies: '前置任务',
    dependents: '后续任务',
    noDependencies: '没有前置任务',
    noDependents: '没有后续任务',
    editDependencies: '编辑前置任务',
    saveDependencies: '保存关系',
    cancelDependencyEdit: '取消',
    dependenciesDescription: '所选任务全部完成后，xopc 才会开始推进当前任务。',
    linkDependencies: '关联前置任务',
    linkedDependencies: '已关联 {{count}} 个前置任务',
    dependencySearchPlaceholder: '搜索任务名称',
    noDependencyMatches: '没有匹配的任务',
    noDependencyCandidates: '没有可选的其他任务',
    removeDependency: '移除前置任务：{{task}}',
    dependencyUpdateFailed: '前置任务更新失败，请刷新后重试。',
    expectedOutputs: '预期输出',
    constraints: '约束与边界',
    approvalRequired: '需要你批准',
    latestResult: '最新结果',
    remainingWork: '还差什么',
    nextAction: '下一步',
    yourDecision: '只需你决定',
    noRemainingWork: '已覆盖全部完成标准。',
    noDecisionNeeded: '暂时不需要你做任何事，xopc 会继续推进。',
    contextUsed: '本次使用的上下文',
    contextSources: '信息来源',
    contextAssumptions: '当前假设',
    contextRisks: '风险',
    contextRoleLabels: { input: '输入', reference: '参考', constraint: '约束', deliverable: '交付物', evidence: '证据' },
    contextKindLabels: { document: '文档', file: '文件', url: '链接', session: '对话', memory: '记忆', task: '任务', artifact: '产物', source: '来源' },
    currentTask: '当前任务',
    executionHistory: '历史执行记录（{{count}}）',
    receiptStatuses: { succeeded: '执行成功', failed: '执行失败', cancelled: '已取消' },
    unresolvedCriteria: '待验证标准',
    resultFeedback: '这件事做好了吗？',
    doneWell: '做好了',
    needsFix: '没做好',
    correctionPlaceholder: '告诉 xopc 哪里不对、你真正想要的结果是什么',
    submitCorrection: '修正并继续',
    feedbackThanks: '收到，我会据此继续改进。',
    correctionStarted: '收到，已重新打开并开始修正。',
    noDefinition: '系统正在进一步明确完成标准。未明确前不会把事情误判为已完成。',
    backToWork: '返回任务列表',
    openTaskConversation: '进入对话',
    taskNotFound: '没有找到这个任务',
    runTask: '开始推进',
    scheduleTask: '安排执行',
    approveTask: '确认完成',
    reopenTask: '重新打开',
    moreActions: '更多操作',
    pauseTask: '暂停推进',
    resumeTask: '继续推进',
    cancelTask: '结束事项',
    actionFailed: '操作失败，请重试。',
    verificationStatuses: {
      passed: '已验证',
      failed: '验证未通过',
      unverified: '待验证',
    },
  } : {
    newWork: 'Ask xopc',
    dialogTitle: 'What do you want to get done?',
    dialogDescription: 'This opens a new conversation. xopc will answer or start working, and create a task only when the work needs ongoing progress.',
    intentLabel: 'Tell xopc what you need',
    intentPlaceholder: 'For example: summarize this week’s meeting notes and suggest next week’s priorities',
    intentSuggestion: 'Summarize this week’s meeting notes and suggest next week’s priorities',
    submit: 'Open conversation and start',
    projectLabel: 'Project',
    monitoringLabel: 'Proactive follow-up',
    monitoringModes: {
      observe: 'Observe only',
      ask_before_action: 'Ask before acting',
      auto_low_risk: 'Auto-run low-risk actions',
    },
    existingProject: 'Existing project',
    newProject: 'New project',
    needsAttention: 'Needs your attention',
    waitingStatus: 'Current status',
    runAttention: 'Run issues',
    running: 'xopc is working',
    continue: 'Continue',
    recent: 'Recent conversations',
    evidenceCount: 'evidence items',
    remainingCount: 'remaining',
    projects: 'Long-term projects',
    emptyRunning: 'No conversations are running',
    emptyContinue: 'No ongoing items yet',
    openChat: 'Open conversation',
    whyNow: 'Why now',
    impact: 'Impact',
    workDone: 'AI checked',
    recommendation: 'Recommendation',
    policyReason: 'Policy decision',
    proposedAction: 'Proposed action',
    actionStates: {
      not_authorized: 'Suggested only; not authorized for auto-run',
      approval_required: 'Waiting for your approval',
      pending: 'Queued to run',
      executing: 'Running',
      completed: 'Auto-run completed',
      rejected: 'Rejected',
      failed: 'Execution failed',
    },
    judgmentReasons: 'Why this is recommended',
    rejectedAlternatives: 'Alternatives not chosen',
    uncertainty: 'Uncertainty',
    snooze: 'Tomorrow',
    dismiss: 'Dismiss',
    feedbackPlaceholder: 'Tell AI how to judge this kind of event next time…',
    applyFeedback: 'Update future judgments',
    taskStatuses: {
      pending: 'Pending',
      planning: 'Defining done',
      waiting_dependency: 'Waiting on dependencies',
      running: 'In progress',
      verifying: 'Verifying',
      needs_user: 'Needs you',
      blocked: 'Blocked',
      paused: 'Paused',
      completed: 'Completed',
      cancelled: 'Ended',
    },
    taskProgress: {
      title: 'xopc owns this task',
      open: 'View task',
      decide: 'Review and decide',
      evidence: 'verified evidence',
      statuses: {
        pending: 'Pending',
        planning: 'Defining done',
        waiting_dependency: 'Waiting on dependencies',
        running: 'In progress',
        verifying: 'Verifying',
        needs_user: 'Needs you',
        blocked: 'Needs you',
        paused: 'Paused',
        completed: 'Completed',
        cancelled: 'Ended',
      },
    },
    detailStatuses: {
      captured: 'Not scheduled',
      ready: 'Ready to start',
      queued: 'Queued',
      running: 'In progress',
      verifying: 'Verifying',
      waiting: 'Waiting',
      blocked: 'Blocked',
      needsUser: 'Needs your attention',
      review: 'Ready for review',
      completed: 'Completed',
      ended: 'Ended',
      paused: 'Ready to continue',
    },
    detailStatusDescriptions: {
      captured: 'This task is captured but has not entered the work queue. Schedule it when you are ready.',
      ready: 'This task is ready for xopc to start.',
      queued: 'This task is queued and will start when resources are available.',
      running: 'xopc is currently working on this task.',
      verifying: 'xopc is checking the result against the completion criteria.',
      waiting: 'This task is waiting for an external condition.',
      blocked: 'A blocking condition must be resolved before work can continue.',
      needsUser: 'xopc needs your input or approval before continuing.',
      review: 'The result is ready for your review.',
      completed: 'This task is complete and closed.',
      ended: 'This task has ended and will not continue.',
      paused: 'This task is not running and can be continued at any time.',
    },
    statusSummary: 'Current status',
    taskLabel: 'Task',
    taskDescription: 'Description and objective',
    editTaskField: 'Edit',
    saveTaskField: 'Save',
    cancelTaskField: 'Cancel',
    noTaskDescription: 'Add background, scope, and delivery requirements.',
    taskProperties: 'Task properties',
    taskPhase: 'Phase',
    priority: 'Priority',
    dueDate: 'Due date',
    executorLabel: 'Agent',
    priorityLabels: { low: 'Low priority', normal: 'Normal priority', high: 'High priority', critical: 'Critical' },
    unassigned: 'No assignee',
    noDueDate: 'No due date',
    updatedAt: 'Updated {{date}}',
    successDefinition: 'Definition of done',
    taskDefinition: 'Task definition',
    criteriaProgress: '{{verified}}/{{total}} verified',
    taskRelations: 'Task relationships',
    dependencies: 'Dependencies',
    dependents: 'Dependent tasks',
    noDependencies: 'No dependencies',
    noDependents: 'No dependent tasks',
    editDependencies: 'Edit dependencies',
    saveDependencies: 'Save relationships',
    cancelDependencyEdit: 'Cancel',
    dependenciesDescription: 'xopc starts this task after every selected task is complete.',
    linkDependencies: 'Link dependencies',
    linkedDependencies: 'Linked dependencies: {{count}}',
    dependencySearchPlaceholder: 'Search tasks',
    noDependencyMatches: 'No matching tasks',
    noDependencyCandidates: 'There are no other tasks to select',
    removeDependency: 'Remove dependency: {{task}}',
    dependencyUpdateFailed: 'Dependencies could not be updated. Refresh and try again.',
    expectedOutputs: 'Expected outputs',
    constraints: 'Constraints and boundaries',
    approvalRequired: 'Your approval is required',
    latestResult: 'Latest result',
    remainingWork: 'What remains',
    nextAction: 'Next action',
    yourDecision: 'Your one decision',
    noRemainingWork: 'All completion criteria are covered.',
    noDecisionNeeded: 'Nothing is needed from you. xopc will keep moving this forward.',
    contextUsed: 'Context used for this task',
    contextSources: 'Sources',
    contextAssumptions: 'Current assumptions',
    contextRisks: 'Risks',
    contextRoleLabels: { input: 'Input', reference: 'Reference', constraint: 'Constraint', deliverable: 'Deliverable', evidence: 'Evidence' },
    contextKindLabels: { document: 'Document', file: 'File', url: 'Link', session: 'Conversation', memory: 'Memory', task: 'Task', artifact: 'Artifact', source: 'Source' },
    currentTask: 'Current task',
    executionHistory: 'Execution history ({{count}})',
    receiptStatuses: { succeeded: 'Succeeded', failed: 'Failed', cancelled: 'Cancelled' },
    unresolvedCriteria: 'Criteria still to verify',
    resultFeedback: 'Was this done well?',
    doneWell: 'Yes, done',
    needsFix: 'Needs fixing',
    correctionPlaceholder: 'Tell xopc what is wrong and what the right task should be',
    submitCorrection: 'Fix and continue',
    feedbackThanks: 'Got it. I will use this to improve future work.',
    correctionStarted: 'Got it. This was reopened and correction has started.',
    noDefinition: 'xopc is still clarifying the completion criteria. It will not mark this done before they are explicit.',
    backToWork: 'Back to tasks',
    openTaskConversation: 'Open conversation',
    taskNotFound: 'This task was not found',
    runTask: 'Start working',
    scheduleTask: 'Schedule work',
    approveTask: 'Mark complete',
    reopenTask: 'Reopen',
    moreActions: 'More actions',
    pauseTask: 'Pause',
    resumeTask: 'Continue',
    cancelTask: 'End task',
    actionFailed: 'The action failed. Please try again.',
    verificationStatuses: {
      passed: 'Verified',
      failed: 'Verification failed',
      unverified: 'Not verified',
    },
  };
}
