import { describe, expect, it, vi } from 'vitest';

import { createBrowserRecipeTool } from '../browser-recipe-tool.js';

describe('browser_recipe tool', () => {
  it('lists enabled and paused workflows for user management', async () => {
    const service = {
      list: () => [
        { id: 'published', name: 'Published', status: 'published', risk: 'read_only', yaml: 'internal-definition' },
        { id: 'disabled', name: 'Disabled', status: 'disabled', risk: 'read_only' },
      ],
    };
    const tool = createBrowserRecipeTool({ getBrowserRecipeService: () => service as never });

    const output = await tool.execute('call-1', { action: 'list' }, new AbortController().signal, () => undefined);

    expect(output.content[0]).toMatchObject({ type: 'text', text: expect.stringContaining('published') });
    expect(JSON.stringify(output)).toContain('disabled');
    expect((output.content[0] as { text: string }).text).toContain('paused');
    expect(JSON.stringify(output)).not.toContain('internal-definition');
  });

  it('saves and enables a workflow generated by the agent', async () => {
    const save = vi.fn(() => ({ id: 'collect-title', name: 'Collect title', status: 'published' }));
    const service = { save };
    const tool = createBrowserRecipeTool({ getBrowserRecipeService: () => service as never });

    const output = await tool.execute(
      'call-1',
      { action: 'save', yaml: 'apiVersion: xopc.ai/browser-recipe/v1' },
      new AbortController().signal,
      () => undefined,
    );

    expect(save).toHaveBeenCalledWith({ yaml: 'apiVersion: xopc.ai/browser-recipe/v1' });
    expect(output.details).toMatchObject({ ok: true, workflow: { id: 'collect-title' } });
  });

  it('enables and disables an existing workflow', async () => {
    const get = vi.fn(() => ({ id: 'collect-title', name: 'Collect title', yaml: 'recipe', status: 'published' }));
    const save = vi.fn(({ status }: { status: string }) => ({ id: 'collect-title', name: 'Collect title', status }));
    const tool = createBrowserRecipeTool({ getBrowserRecipeService: () => ({ get, save }) as never });

    await tool.execute('call-1', { action: 'disable', recipeId: 'collect-title' }, new AbortController().signal, () => undefined);

    expect(save).toHaveBeenCalledWith({ yaml: 'recipe', status: 'disabled', expectedId: 'collect-title' });
  });

  it('waits for a recipe run and returns its persisted result', async () => {
    const runAndWait = vi.fn(async () => ({ id: 'run-1', status: 'succeeded', result: { title: 'Example' } }));
    const service = { runAndWait };
    const tool = createBrowserRecipeTool({ getBrowserRecipeService: () => service as never });

    const output = await tool.execute(
      'call-1',
      { action: 'run', recipeId: 'collect-title', args: { query: 'xopc' } },
      new AbortController().signal,
      () => undefined,
    );

    expect(runAndWait).toHaveBeenCalledWith('collect-title', { query: 'xopc' }, expect.any(AbortSignal));
    expect(output.details).toMatchObject({ ok: true, run: { id: 'run-1', status: 'succeeded' } });
  });
});
