import type { StoredLanguage } from '@/lib/storage';

import type { WorkflowCardLabels } from './workflow-card';
import type { WorkflowAgentInlineDetailLabels } from './workflow-agent-inline-detail';

export function workflowCardLabels(language: StoredLanguage): WorkflowCardLabels {
  if (language === 'zh') return zhLabels();
  return enLabels();
}

function checkDetailLabelsEn(): WorkflowAgentInlineDetailLabels {
  return {
    close: 'Close',
    statusQueued: 'Queued',
    statusRunning: 'Running',
    statusDone: 'Completed',
    statusError: 'Failed',
    statusSkipped: 'Skipped',
    workedFor: (d) => `Worked for ${d}`,
    statusHeading: 'Status',
    phaseHeading: 'Phase',
    elapsedHeading: 'Elapsed',
    currentStepHeading: 'Current step',
    executionHeading: 'Execution process',
    outputHeading: 'Output',
    stepsHeading: 'Steps',
    transcriptHeading: 'Transcript',
    promptHeading: 'Prompt',
    logsHeading: 'Workflow logs',
    runningPlaceholder: 'Waiting for check updates…',
  };
}

function checkDetailLabelsZh(): WorkflowAgentInlineDetailLabels {
  return {
    close: '关闭',
    statusQueued: '排队中',
    statusRunning: '运行中',
    statusDone: '已完成',
    statusError: '失败',
    statusSkipped: '已跳过',
    workedFor: (d) => `已运行 ${d}`,
    statusHeading: '状态',
    phaseHeading: '阶段',
    elapsedHeading: '耗时',
    currentStepHeading: '当前步骤',
    executionHeading: '执行过程',
    outputHeading: '产出',
    stepsHeading: '步骤',
    transcriptHeading: 'Transcript',
    promptHeading: '输入',
    logsHeading: '工作流日志',
    runningPlaceholder: '等待检查项更新…',
  };
}

function enLabels(): WorkflowCardLabels {
  return {
    header: {
      collapse: 'Collapse',
      expand: 'Expand',
      runningMeta: (count, duration) =>
        duration ? `${count} · ${duration}` : `${count}`,
      completedMeta: (count, duration) =>
        duration ? `✓ ${count} · ${duration}` : `✓ ${count}`,
      failedMeta: 'failed',
    },
    phase: {
      countTpl: (done, total) => `${done}/${total}`,
      runningTag: (n) => `· ${n} running`,
      errorsTag: (n) => `· ${n} errors`,
      skippedTag: (n) => `· ${n} skipped`,
      showPrompt: 'Show prompt',
      hidePrompt: 'Hide prompt',
      promptHeading: 'Prompt',
      resultPreviewHeading: 'Result',
      errorHeading: 'Error',
      emptyPreview: '(no preview)',
      agentNumber: (n) => `Check ${n}`,
      queued: 'Queued',
      running: 'Running…',
      openDetail: 'View check details',
    },
    checkDetail: checkDetailLabelsEn(),
    result: {
      topFindingsHeading: (n) => `Top findings (${n})`,
      topRisksHeading: (n) => `Top risks (${n})`,
      executiveSummaryHeading: 'Executive summary',
      summaryHeading: 'Summary',
      openQuestionsHeading: 'Open questions',
      conclusionHeading: 'Conclusion',
      recommendationsHeading: 'Recommendations',
      nextStepsHeading: 'Next steps',
      checklistHeading: 'Checklist',
      moreSuffix: (n) => `${n} more…`,
      emptyResult: '(no result)',
    },
    error: {
      titleValidation: 'Workflow setup needs attention',
      titleAbort: 'Workflow aborted',
      titleTimeout: 'Workflow timed out',
      titleRuntime: 'Workflow failed',
      expand: 'Expand details',
      collapse: 'Collapse details',
      expandHint: 'Click to see error details',
      detailsHeading: 'Failure reason',
      impactHeading: 'Impact',
      recoveryHeading: 'Recommended actions',
      recoveryActions: {
        validation_error: ['Open the workflow and review the highlighted steps.', 'Reconnect any step that cannot reach the final result.'],
        aborted: ['The run was stopped. Start it again if you still need the result.'],
        timeout: ['Retry the workflow.', 'If it times out again, reduce concurrency or check model/API availability.'],
        runtime_error: ['Review the failed check first.', 'Use completed check results if they are still relevant.', 'Copy the error details if you want to continue diagnosis.'],
      },
      logsHeading: 'Technical logs',
      failedAgentsHeading: 'Check status',
      executedAgentsHeading: 'Check status',
      progressHeading: 'Execution process',
      noExtraDetails: 'No additional details recorded.',
      copyReason: 'Copy',
      copyReasonDone: 'Copied',
      impactTpl: (done, total, failed) => `${done}/${total} checks completed · ${failed} need attention`,
      phase: {
        countTpl: (done, total) => `${done}/${total}`,
        runningTag: (n) => `· ${n} running`,
        errorsTag: (n) => `· ${n} errors`,
        skippedTag: (n) => `· ${n} skipped`,
        showPrompt: 'Show prompt',
        hidePrompt: 'Hide prompt',
        promptHeading: 'Prompt',
        resultPreviewHeading: 'Result',
        errorHeading: 'Error',
        emptyPreview: '(no preview)',
        agentNumber: (n) => `Check ${n}`,
        queued: 'Queued',
        running: 'Running…',
        openDetail: 'View check details',
      },
    },
    saveAria: 'Copy and edit workflow…',
    saveTitle: 'Open a copied workflow draft in the Workflows center',
    copyAria: 'Copy result',
    copyDoneAria: 'Copied',
    openInWorkflowsAria: 'Open task details',
    openInWorkflowsTitle: 'Open this task in the task center',
    viewSubagentsHeading: 'View checks',
    runningProgressHeading: 'Current progress',
    runningAgentsHeading: 'Running checks',
    completedAgentsHeading: 'Completed checks',
    queuedAgentsHeading: 'Queued checks',
    failedAgentsHeading: 'Needs attention',
    currentProgressTpl: (phase, running, done, total) => {
      const phaseText = phase ? `Step: ${phase}` : 'Task is running';
      return `${phaseText} · ${running} running · ${done}/${total} completed`;
    },
    recentLogsHeading: 'Recent updates',
    showAllLogs: 'Show all',
    live: {
      details: 'Details',
      openRun: 'Open run',
      stop: 'Stop',
      close: 'Close workflow details',
      title: 'Task',
      overview: 'Overview',
      agents: 'Checks',
      logs: 'Logs',
      result: 'Result',
      currentState: 'Current state',
      runId: 'Run ID',
      elapsed: 'Elapsed',
      progress: (done, total) => `${done}/${total} checks`,
      activeFallback: 'Task is running',
      noResult: 'No result recorded yet.',
      status: {
        queued: 'Queued',
        running: 'Running',
        succeeded: 'Completed',
        failed: 'Failed',
        cancelled: 'Cancelled',
        timeout: 'Timed out',
      },
    },
  };
}

function zhLabels(): WorkflowCardLabels {
  return {
    header: {
      collapse: '收起',
      expand: '展开',
      runningMeta: (count, duration) => (duration ? `${count} · ${duration}` : `${count}`),
      completedMeta: (count, duration) => (duration ? `✓ ${count} · ${duration}` : `✓ ${count}`),
      failedMeta: '失败',
    },
    phase: {
      countTpl: (done, total) => `${done}/${total}`,
      runningTag: (n) => `· ${n} 运行中`,
      errorsTag: (n) => `· ${n} 失败`,
      skippedTag: (n) => `· ${n} 已跳过`,
      showPrompt: '查看 prompt',
      hidePrompt: '收起 prompt',
      promptHeading: 'Prompt',
      resultPreviewHeading: '结果预览',
      errorHeading: '错误',
      emptyPreview: '（暂无预览）',
      agentNumber: (n) => `检查 ${n}`,
      queued: '排队中',
      running: '运行中…',
      openDetail: '查看检查项详情',
    },
    checkDetail: checkDetailLabelsZh(),
    result: {
      topFindingsHeading: (n) => `主要发现（${n}）`,
      topRisksHeading: (n) => `主要风险（${n}）`,
      executiveSummaryHeading: '摘要',
      summaryHeading: '总结',
      openQuestionsHeading: '待解决的问题',
      conclusionHeading: '结论',
      recommendationsHeading: '处理建议',
      nextStepsHeading: '建议下一步',
      checklistHeading: '检查清单',
      moreSuffix: (n) => `还有 ${n} 条…`,
      emptyResult: '（无结果）',
    },
    error: {
      titleValidation: '工作流配置需要处理',
      titleAbort: '工作流已中止',
      titleTimeout: '工作流超时',
      titleRuntime: '工作流执行失败',
      expand: '展开详情',
      collapse: '收起详情',
      expandHint: '点击查看错误详情',
      detailsHeading: '失败原因',
      impactHeading: '影响范围',
      recoveryHeading: '建议处理',
      recoveryActions: {
        validation_error: ['打开工作流并查看高亮的问题步骤。', '重新连接无法到达最终结果的步骤。'],
        aborted: ['本次执行已停止。如仍需要结果，可以重新运行。'],
        timeout: ['重新运行工作流。', '如果仍然超时，建议降低并发或检查模型/API 可用性。'],
        runtime_error: ['优先查看失败检查项。', '已完成检查项的结果仍可按需参考。', '需要继续诊断时，可以复制错误详情。'],
      },
      logsHeading: '技术日志',
      failedAgentsHeading: '检查项状态',
      executedAgentsHeading: '检查项状态',
      progressHeading: '执行过程',
      noExtraDetails: '没有更多诊断信息。',
      copyReason: '复制',
      copyReasonDone: '已复制',
      impactTpl: (done, total, failed) => `已完成 ${done}/${total} 个检查项 · ${failed} 个需要关注`,
      phase: {
        countTpl: (done, total) => `${done}/${total}`,
        runningTag: (n) => `· ${n} 运行中`,
        errorsTag: (n) => `· ${n} 失败`,
        skippedTag: (n) => `· ${n} 已跳过`,
        showPrompt: '查看 prompt',
        hidePrompt: '收起 prompt',
        promptHeading: 'Prompt',
        resultPreviewHeading: '结果预览',
        errorHeading: '错误',
        emptyPreview: '（暂无预览）',
        agentNumber: (n) => `检查 ${n}`,
        queued: '排队中',
        running: '运行中…',
        openDetail: '查看检查项详情',
      },
    },
    saveAria: '复制并编辑工作流…',
    saveTitle: '在工作流中心打开复制草案',
    copyAria: '复制结果',
    copyDoneAria: '已复制',
    openInWorkflowsAria: '打开任务详情',
    openInWorkflowsTitle: '在任务中心查看此任务',
    viewSubagentsHeading: '查看检查项',
    runningProgressHeading: '当前进展',
    runningAgentsHeading: '正在检查',
    completedAgentsHeading: '已完成检查',
    queuedAgentsHeading: '等待检查',
    failedAgentsHeading: '需要关注',
    currentProgressTpl: (phase, running, done, total) => {
      const phaseText = phase ? `正在执行 ${phase}` : '任务正在执行';
      return `${phaseText} · ${running} 个运行中 · 已完成 ${done}/${total}`;
    },
    recentLogsHeading: '最近更新',
    showAllLogs: '显示全部',
    live: {
      details: '详情',
      openRun: '打开运行',
      stop: '停止',
      close: '关闭工作流详情',
      title: '任务',
      overview: '概览',
      agents: '检查项',
      logs: '日志',
      result: '结果',
      currentState: '当前状态',
      runId: '运行 ID',
      elapsed: '耗时',
      progress: (done, total) => `${done}/${total} 个检查项`,
      activeFallback: '任务正在执行',
      noResult: '暂无结果。',
      status: {
        queued: '排队中',
        running: '运行中',
        succeeded: '已完成',
        failed: '失败',
        cancelled: '已取消',
        timeout: '超时',
      },
    },
  };
}
