import {
  type EndpointToolDefinition,
  type EndpointToolExecutionResult,
} from '@xopcai/endpoint-tools-client';
import {
  ENDPOINT_FILE_OUTPUT_SCHEMA,
  ENDPOINT_MAX_FILE_BYTES,
  ENDPOINT_TEXT_OUTPUT_SCHEMA,
} from '@xopcai/endpoint-tools-protocol';
import * as Clipboard from 'expo-clipboard';
import { randomUUID } from 'expo-crypto';
import * as Device from 'expo-device';
import * as DocumentPicker from 'expo-document-picker';
import { Directory, File, Paths } from 'expo-file-system';
import * as Linking from 'expo-linking';
import * as Sharing from 'expo-sharing';

import { showLocalMobileNotification } from '../notifications/mobile-notifications';
import { CONTACT_ENDPOINT_TOOL_DEFINITIONS } from './modules/contacts';

function textResult(text: string): EndpointToolExecutionResult {
  return { content: [{ type: 'text', text }] };
}

function userCancelled(message: string): Error {
  const error = new Error(message);
  error.name = 'AbortError';
  return error;
}

function exactStringArgument(
  args: Record<string, unknown>,
  name: string,
  maxLength: number,
): string {
  if (Object.keys(args).length !== 1 || typeof args[name] !== 'string') {
    throw new TypeError(`Expected exactly one string argument: ${name}`);
  }
  const value = args[name];
  if (!value || value.length > maxLength) throw new TypeError(`Invalid ${name}`);
  return value;
}

function mimeTypeForName(name: string): string {
  const extension = name.split('.').pop()?.toLowerCase();
  if (extension === 'json') return 'application/json';
  if (extension === 'md') return 'text/markdown';
  if (extension === 'csv') return 'text/csv';
  if (extension === 'txt') return 'text/plain';
  return 'text/plain';
}

export const MOBILE_ENDPOINT_TOOL_DEFINITIONS: readonly EndpointToolDefinition[] = [
  ...CONTACT_ENDPOINT_TOOL_DEFINITIONS,
  {
    descriptor: {
      name: 'mobile.file.pick',
      title: 'Choose a local file',
      description: 'Ask the user to choose one file and make it available to the agent.',
      inputSchema: { type: 'object', additionalProperties: false, properties: {} },
      outputSchema: ENDPOINT_FILE_OUTPUT_SCHEMA,
      policyId: 'personal.foreground-read',
      sensitivity: 'personal',
      effect: 'read',
      confirmation: 'always',
      requiresForeground: true,
      requiredPermissions: ['file-read'],
      timeoutMs: 120_000,
      maxConcurrency: 1,
      supportsCancellation: false,
      idempotent: false,
      resultKinds: ['file'],
    },
    async execute(args, context) {
      if (Object.keys(args).length !== 0) throw new TypeError('Expected no arguments');
      const result = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: true, multiple: false });
      if (result.canceled) throw userCancelled('File selection cancelled');
      const asset = result.assets[0];
      if (!asset?.uri) throw new Error('Selected file is unavailable');
      if (asset.size !== undefined && asset.size > ENDPOINT_MAX_FILE_BYTES) {
        throw new TypeError(`Selected file exceeds ${ENDPOINT_MAX_FILE_BYTES} bytes`);
      }
      const response = await fetch(asset.uri);
      if (!response.ok) throw new Error('Selected file could not be read');
      const bytes = new Uint8Array(await response.arrayBuffer());
      if (bytes.byteLength > ENDPOINT_MAX_FILE_BYTES) {
        throw new TypeError(`Selected file exceeds ${ENDPOINT_MAX_FILE_BYTES} bytes`);
      }
      const name = asset.name || `file-${Date.now()}`;
      return { content: [await context.uploadFile({
        name,
        mimeType: asset.mimeType || 'application/octet-stream',
        bytes,
      })] };
    },
  },
  {
    descriptor: {
      name: 'mobile.file.share',
      title: 'Share a text file',
      description: 'Open the system share sheet for a bounded UTF-8 text file generated by the agent.',
      inputSchema: {
        type: 'object',
        additionalProperties: false,
        required: ['suggestedName', 'content'],
        properties: {
          suggestedName: { type: 'string', minLength: 1, maxLength: 255 },
          content: { type: 'string', maxLength: 200_000 },
        },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write',
      confirmation: 'always',
      requiresForeground: true,
      requiredPermissions: ['file-share'],
      timeoutMs: 120_000,
      maxConcurrency: 1,
      supportsCancellation: false,
      idempotent: false,
      resultKinds: ['text'],
    },
    async execute(args) {
      const suggestedName = args.suggestedName;
      const content = args.content;
      if (
        Object.keys(args).length !== 2
        || typeof suggestedName !== 'string'
        || !suggestedName
        || suggestedName === '.'
        || suggestedName === '..'
        || suggestedName.length > 255
        || suggestedName.includes('/')
        || suggestedName.includes('\\')
        || typeof content !== 'string'
        || content.length > 200_000
        || new TextEncoder().encode(content).byteLength > 200 * 1024
      ) {
        throw new TypeError('Invalid file share arguments');
      }
      if (!(await Sharing.isAvailableAsync())) throw new Error('System sharing is unavailable');
      const directory = new Directory(Paths.cache, 'endpoint-tools', randomUUID());
      directory.create({ intermediates: true });
      const file = new File(directory, suggestedName);
      try {
        file.create();
        file.write(content);
        await Sharing.shareAsync(file.uri, {
          mimeType: mimeTypeForName(suggestedName),
          dialogTitle: 'Share file from xopc',
        });
      } finally {
        try {
          directory.delete();
        } catch {
          // The share side effect is complete; cleanup failure must not make the agent retry it.
        }
      }
      return textResult(`Shared ${suggestedName}`);
    },
  },
  {
    descriptor: {
      name: 'mobile.notification.show',
      title: 'Show a notification',
      description: 'Show a bounded local notification after user confirmation.',
      inputSchema: {
        type: 'object',
        additionalProperties: false,
        required: ['title', 'body'],
        properties: {
          title: { type: 'string', minLength: 1, maxLength: 120 },
          body: { type: 'string', minLength: 1, maxLength: 500 },
        },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write',
      confirmation: 'always',
      requiresForeground: true,
      requiredPermissions: ['notifications'],
      timeoutMs: 10_000,
      maxConcurrency: 1,
      supportsCancellation: false,
      idempotent: false,
      resultKinds: ['text'],
    },
    async execute(args) {
      const title = args.title;
      const body = args.body;
      if (
        Object.keys(args).length !== 2
        || typeof title !== 'string'
        || !title.trim()
        || title.length > 120
        || typeof body !== 'string'
        || !body.trim()
        || body.length > 500
      ) {
        throw new TypeError('Invalid notification arguments');
      }
      await showLocalMobileNotification(title, body);
      return textResult('Notification shown.');
    },
  },
  {
    descriptor: {
      name: 'mobile.device.get_info',
      title: 'Read device information',
      description: 'Read the mobile device model and operating-system version.',
      inputSchema: { type: 'object', additionalProperties: false, properties: {} },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'public.background-read',
      sensitivity: 'public',
      effect: 'read',
      confirmation: 'never',
      requiresForeground: false,
      requiredPermissions: [],
      timeoutMs: 10_000,
      maxConcurrency: 2,
      supportsCancellation: false,
      idempotent: true,
      resultKinds: ['text'],
    },
    async execute(args) {
      if (Object.keys(args).length !== 0) throw new TypeError('Expected no arguments');
      return textResult(JSON.stringify({
        brand: Device.brand,
        manufacturer: Device.manufacturer,
        modelName: Device.modelName,
        osName: Device.osName,
        osVersion: Device.osVersion,
      }));
    },
  },
  {
    descriptor: {
      name: 'mobile.clipboard.write',
      title: 'Write to the clipboard',
      description: 'Replace the mobile clipboard with plain text.',
      inputSchema: {
        type: 'object',
        additionalProperties: false,
        required: ['text'],
        properties: { text: { type: 'string', minLength: 1, maxLength: 100_000 } },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write',
      confirmation: 'always',
      requiresForeground: true,
      requiredPermissions: ['clipboard-write'],
      timeoutMs: 10_000,
      maxConcurrency: 1,
      supportsCancellation: false,
      idempotent: true,
      resultKinds: ['text'],
    },
    async execute(args) {
      await Clipboard.setStringAsync(exactStringArgument(args, 'text', 100_000));
      return textResult('Clipboard updated.');
    },
  },
  {
    descriptor: {
      name: 'mobile.app.open_url',
      title: 'Open an external URL',
      description: 'Open an HTTP or HTTPS URL in a mobile application.',
      inputSchema: {
        type: 'object',
        additionalProperties: false,
        required: ['url'],
        properties: { url: { type: 'string', minLength: 1, maxLength: 2_048 } },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write',
      confirmation: 'always',
      requiresForeground: true,
      requiredPermissions: ['open-external-url'],
      timeoutMs: 15_000,
      maxConcurrency: 1,
      supportsCancellation: false,
      idempotent: false,
      resultKinds: ['text'],
    },
    async execute(args) {
      const raw = exactStringArgument(args, 'url', 2_048);
      const url = new URL(raw);
      if (url.protocol !== 'http:' && url.protocol !== 'https:') {
        throw new TypeError('Only HTTP and HTTPS URLs are allowed');
      }
      await Linking.openURL(url.href);
      return textResult(`Opened ${url.href}`);
    },
  },
];
