import { getSqliteDatabase, runSqliteWriteTransaction } from '../../storage/sqlite/index.js';
import type { BrowserAutomation, BrowserAutomationRun, BrowserAutomationRunEvent } from './types.js';

type AutomationRow = { automation_id: string; revision: number; status: BrowserAutomation['status']; definition_json: string; created_at_ms: number; updated_at_ms: number };
type RunRow = { run_id: string; automation_id: string; automation_revision: number; definition_json: string; status: BrowserAutomationRun['status']; inputs_json: string; result_json: string | null; error: string | null; created_at_ms: number; started_at_ms: number | null; ended_at_ms: number | null; duration_ms: number | null };
type EventRow = { event_id: string; run_id: string; seq: number; type: string; data_json: string | null; created_at_ms: number };

const AUTOMATION_SELECT = 'SELECT automation_id, revision, status, definition_json, created_at_ms, updated_at_ms FROM browser_automations';
const RUN_SELECT = 'SELECT run_id, automation_id, automation_revision, definition_json, status, inputs_json, result_json, error, created_at_ms, started_at_ms, ended_at_ms, duration_ms FROM browser_automation_runs';

const parseAutomation = (row: AutomationRow): BrowserAutomation => ({ id: row.automation_id, revision: row.revision, status: row.status, definition: JSON.parse(row.definition_json), createdAtMs: row.created_at_ms, updatedAtMs: row.updated_at_ms });
const parseRun = (row: RunRow): BrowserAutomationRun => ({ id: row.run_id, automationId: row.automation_id, automationRevision: row.automation_revision, definition: JSON.parse(row.definition_json), status: row.status, inputs: JSON.parse(row.inputs_json), result: row.result_json ? JSON.parse(row.result_json) : undefined, error: row.error ?? undefined, createdAtMs: row.created_at_ms, startedAtMs: row.started_at_ms ?? undefined, endedAtMs: row.ended_at_ms ?? undefined, durationMs: row.duration_ms ?? undefined });

export const listBrowserAutomations = (): BrowserAutomation[] => (getSqliteDatabase().prepare(`${AUTOMATION_SELECT} ORDER BY updated_at_ms DESC`).all() as AutomationRow[]).map(parseAutomation);
export const getBrowserAutomation = (id: string): BrowserAutomation | null => { const row = getSqliteDatabase().prepare(`${AUTOMATION_SELECT} WHERE automation_id = ?`).get(id) as AutomationRow | undefined; return row ? parseAutomation(row) : null; };
export function saveBrowserAutomation(value: BrowserAutomation): void { runSqliteWriteTransaction((db) => db.prepare('INSERT INTO browser_automations (automation_id, revision, status, definition_json, created_at_ms, updated_at_ms) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(automation_id) DO UPDATE SET revision=excluded.revision, status=excluded.status, definition_json=excluded.definition_json, updated_at_ms=excluded.updated_at_ms').run(value.id, value.revision, value.status, JSON.stringify(value.definition), value.createdAtMs, value.updatedAtMs)); }
export const deleteBrowserAutomation = (id: string): boolean => runSqliteWriteTransaction((db) => db.prepare('DELETE FROM browser_automations WHERE automation_id = ?').run(id).changes > 0);

export function saveBrowserAutomationRun(value: BrowserAutomationRun): void { runSqliteWriteTransaction((db) => db.prepare('INSERT INTO browser_automation_runs (run_id, automation_id, automation_revision, definition_json, status, inputs_json, result_json, error, created_at_ms, started_at_ms, ended_at_ms, duration_ms) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(run_id) DO UPDATE SET status=excluded.status, result_json=excluded.result_json, error=excluded.error, started_at_ms=excluded.started_at_ms, ended_at_ms=excluded.ended_at_ms, duration_ms=excluded.duration_ms').run(value.id, value.automationId, value.automationRevision, JSON.stringify(value.definition), value.status, JSON.stringify(value.inputs), value.result === undefined ? null : JSON.stringify(value.result), value.error ?? null, value.createdAtMs, value.startedAtMs ?? null, value.endedAtMs ?? null, value.durationMs ?? null)); }
export const getBrowserAutomationRun = (id: string): BrowserAutomationRun | null => { const row = getSqliteDatabase().prepare(`${RUN_SELECT} WHERE run_id = ?`).get(id) as RunRow | undefined; return row ? parseRun(row) : null; };
export const listBrowserAutomationRuns = (automationId?: string): BrowserAutomationRun[] => ((automationId ? getSqliteDatabase().prepare(`${RUN_SELECT} WHERE automation_id = ? ORDER BY created_at_ms DESC`).all(automationId) : getSqliteDatabase().prepare(`${RUN_SELECT} ORDER BY created_at_ms DESC`).all()) as RunRow[]).map(parseRun);
export const listActiveBrowserAutomationRuns = (): BrowserAutomationRun[] => (getSqliteDatabase().prepare(`${RUN_SELECT} WHERE status IN ('queued', 'running')`).all() as RunRow[]).map(parseRun);
export const hasActiveBrowserAutomationRuns = (automationId: string): boolean => Boolean(getSqliteDatabase().prepare("SELECT 1 FROM browser_automation_runs WHERE automation_id = ? AND status IN ('queued', 'running') LIMIT 1").get(automationId));
export const nextBrowserAutomationRunEventSeq = (runId: string): number => ((getSqliteDatabase().prepare('SELECT COALESCE(MAX(seq), 0) + 1 AS seq FROM browser_action_audit WHERE run_id = ?').get(runId) as { seq: number }).seq);
export function appendBrowserAutomationRunEvent(value: BrowserAutomationRunEvent): void { runSqliteWriteTransaction((db) => db.prepare('INSERT INTO browser_action_audit (event_id, run_id, seq, type, data_json, created_at_ms) VALUES (?, ?, ?, ?, ?, ?)').run(value.id, value.runId, value.seq, value.type, value.data === undefined ? null : JSON.stringify(value.data), value.createdAtMs)); }
export const listBrowserAutomationRunEvents = (runId: string): BrowserAutomationRunEvent[] => (getSqliteDatabase().prepare('SELECT event_id, run_id, seq, type, data_json, created_at_ms FROM browser_action_audit WHERE run_id = ? ORDER BY seq').all(runId) as EventRow[]).map((row) => ({ id: row.event_id, runId: row.run_id, seq: row.seq, type: row.type, data: row.data_json ? JSON.parse(row.data_json) : undefined, createdAtMs: row.created_at_ms }));
