export function workCopy(language: 'en' | 'zh') {
  return language === 'zh' ? {
    newWork: '交给 xopc',
    dialogTitle: '现在想完成什么？',
    dialogDescription: '发送后会直接进入对话，xopc 会立即开始处理。',
    intentLabel: '告诉 xopc 你要做什么',
    intentPlaceholder: '例如：整理这周的会议记录，提炼待办并给出下周优先级',
    submit: '进入对话',
    needsAttention: '需要你处理',
    runAttention: '运行异常',
    running: 'xopc 正在处理',
    continue: '继续推进',
    recent: '最近对话',
    projects: '长期项目',
    emptyRunning: '当前没有正在处理的对话',
    emptyContinue: '还没有需要继续推进的事项',
    openChat: '打开对话',
    whyNow: '为什么现在',
    impact: '影响',
    workDone: 'AI 已完成',
    recommendation: '建议',
    snooze: '明天再看',
    dismiss: '忽略',
    feedbackPlaceholder: '告诉 AI：以后遇到这类情况应该怎样判断…',
    applyFeedback: '调整后续判断',
  } : {
    newWork: 'Ask xopc',
    dialogTitle: 'What do you want to get done?',
    dialogDescription: 'You will enter a conversation immediately and xopc will start working.',
    intentLabel: 'Tell xopc what you need',
    intentPlaceholder: 'For example: summarize this week’s meeting notes and suggest next week’s priorities',
    submit: 'Open conversation',
    needsAttention: 'Needs your attention',
    runAttention: 'Run issues',
    running: 'xopc is working',
    continue: 'Continue',
    recent: 'Recent conversations',
    projects: 'Long-term projects',
    emptyRunning: 'No conversations are running',
    emptyContinue: 'No ongoing items yet',
    openChat: 'Open conversation',
    whyNow: 'Why now',
    impact: 'Impact',
    workDone: 'AI checked',
    recommendation: 'Recommendation',
    snooze: 'Tomorrow',
    dismiss: 'Dismiss',
    feedbackPlaceholder: 'Tell AI how to judge this kind of event next time…',
    applyFeedback: 'Update future judgments',
  };
}
