export function workCopy(language: 'en' | 'zh') {
  return language === 'zh' ? {
    newWork: '交给 xopc',
    dialogTitle: '现在想完成什么？',
    dialogDescription: '发送后会直接进入对话，xopc 会立即开始处理。',
    intentLabel: '告诉 xopc 你要做什么',
    intentPlaceholder: '例如：整理这周的会议记录，提炼待办并给出下周优先级',
    submit: '进入对话',
    needsAttention: '等你决定',
    running: 'xopc 正在处理',
    continue: '继续推进',
    recent: '最近对话',
    focuses: '持续关注',
    projects: '长期项目',
    emptyRunning: '当前没有正在处理的对话',
    emptyContinue: '还没有需要继续推进的事项',
    openChat: '打开对话',
  } : {
    newWork: 'Ask xopc',
    dialogTitle: 'What do you want to get done?',
    dialogDescription: 'You will enter a conversation immediately and xopc will start working.',
    intentLabel: 'Tell xopc what you need',
    intentPlaceholder: 'For example: summarize this week’s meeting notes and suggest next week’s priorities',
    submit: 'Open conversation',
    needsAttention: 'Needs your decision',
    running: 'xopc is working',
    continue: 'Continue',
    recent: 'Recent conversations',
    focuses: 'Ongoing focuses',
    projects: 'Long-term projects',
    emptyRunning: 'No conversations are running',
    emptyContinue: 'No ongoing items yet',
    openChat: 'Open conversation',
  };
}
