export function workCopy(language: 'en' | 'zh') {
  return language === 'zh' ? {
    newWork: '交给 xopc',
    dialogTitle: '现在想完成什么？',
    dialogDescription: 'xopc 会先理解目标、归属项目和下一步，由你确认后再建立工作。',
    intentLabel: '告诉 xopc 你要做什么',
    intentPlaceholder: '例如：整理这周的会议记录，提炼待办并给出下周优先级',
    submit: '生成工作方案',
    proposalTitle: '确认工作方案',
    projectLabel: '归属项目',
    outcomeLabel: '期望结果',
    nextActionLabel: '第一步',
    monitoringLabel: '主动跟进',
    monitoringModes: {
      observe: '仅观察',
      ask_before_action: '行动前询问',
      auto_low_risk: '自动执行低风险操作',
    },
    existingProject: '已有项目',
    newProject: '新项目',
    editIntent: '返回修改',
    confirmWork: '确认并建立工作',
    needsAttention: '需要你处理',
    runAttention: '运行异常',
    running: 'xopc 正在处理',
    continue: '继续推进',
    recent: '最近对话',
    recentOutcomes: '最近完成',
    evidenceCount: '项证据',
    remainingCount: '项待继续',
    projects: '长期项目',
    emptyRunning: '当前没有正在处理的对话',
    emptyContinue: '还没有需要继续推进的事项',
    openChat: '打开对话',
    whyNow: '为什么现在',
    impact: '影响',
    workDone: 'AI 已完成',
    recommendation: '建议',
    snooze: '明天再看',
    dismiss: '忽略',
    feedbackPlaceholder: '告诉 AI：以后遇到这类情况应该怎样判断…',
    applyFeedback: '调整后续判断',
    outcomeStatuses: {
      running: '正在推进',
      needs_user: '需要你',
      completed: '已完成',
    },
    successDefinition: '怎样才算完成',
    deliverables: '交付物',
    constraints: '约束与边界',
    approvalRequired: '需要你批准',
    executionReceipts: '执行回执',
    noDefinition: '系统正在进一步明确完成标准。未明确前不会把事情误判为已完成。',
    noReceipts: '还没有执行回执。',
    backToWork: '返回首页',
    outcomeNotFound: '没有找到这个结果',
    runOutcome: '开始推进',
    pauseOutcome: '暂时暂停',
    resumeOutcome: '继续推进',
    cancelOutcome: '结束事项',
    actionFailed: '操作失败，请重试。',
    verificationStatuses: {
      passed: '已验证',
      failed: '验证未通过',
      unverified: '待验证',
    },
  } : {
    newWork: 'Ask xopc',
    dialogTitle: 'What do you want to get done?',
    dialogDescription: 'xopc will clarify the outcome, project, and first action before creating the work.',
    intentLabel: 'Tell xopc what you need',
    intentPlaceholder: 'For example: summarize this week’s meeting notes and suggest next week’s priorities',
    submit: 'Prepare work plan',
    proposalTitle: 'Confirm work plan',
    projectLabel: 'Project',
    outcomeLabel: 'Desired outcome',
    nextActionLabel: 'First action',
    monitoringLabel: 'Proactive follow-up',
    monitoringModes: {
      observe: 'Observe only',
      ask_before_action: 'Ask before acting',
      auto_low_risk: 'Auto-run low-risk actions',
    },
    existingProject: 'Existing project',
    newProject: 'New project',
    editIntent: 'Edit intent',
    confirmWork: 'Confirm and create',
    needsAttention: 'Needs your attention',
    runAttention: 'Run issues',
    running: 'xopc is working',
    continue: 'Continue',
    recent: 'Recent conversations',
    recentOutcomes: 'Recent outcomes',
    evidenceCount: 'evidence items',
    remainingCount: 'remaining',
    projects: 'Long-term projects',
    emptyRunning: 'No conversations are running',
    emptyContinue: 'No ongoing items yet',
    openChat: 'Open conversation',
    whyNow: 'Why now',
    impact: 'Impact',
    workDone: 'AI checked',
    recommendation: 'Recommendation',
    snooze: 'Tomorrow',
    dismiss: 'Dismiss',
    feedbackPlaceholder: 'Tell AI how to judge this kind of event next time…',
    applyFeedback: 'Update future judgments',
    outcomeStatuses: {
      running: 'In progress',
      needs_user: 'Needs you',
      completed: 'Completed',
    },
    successDefinition: 'Definition of done',
    deliverables: 'Deliverables',
    constraints: 'Constraints and boundaries',
    approvalRequired: 'Your approval is required',
    executionReceipts: 'Execution receipts',
    noDefinition: 'xopc is still clarifying the completion criteria. It will not mark this done before they are explicit.',
    noReceipts: 'No execution receipts yet.',
    backToWork: 'Back to home',
    outcomeNotFound: 'This outcome was not found',
    runOutcome: 'Start working',
    pauseOutcome: 'Pause',
    resumeOutcome: 'Continue',
    cancelOutcome: 'End outcome',
    actionFailed: 'The action failed. Please try again.',
    verificationStatuses: {
      passed: 'Verified',
      failed: 'Verification failed',
      unverified: 'Not verified',
    },
  };
}
