import {
  ENDPOINT_MAX_FILE_BYTES,
  type EndpointToolDescriptor,
} from '@xopcai/endpoint-tools-protocol';

import type { EndpointToolExecutionContext, EndpointToolExecutionResult } from './host';

const textArgumentSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['text'],
  properties: { text: { type: 'string', minLength: 1, maxLength: 100_000 } },
};

export const DESKTOP_ENDPOINT_TOOLS: readonly EndpointToolDescriptor[] = [
  {
    name: 'desktop.file.pick',
    title: 'Choose a local file',
    description: 'Ask the user to choose one local file and make it available to the agent.',
    inputSchema: { type: 'object', additionalProperties: false, properties: {} },
    effect: 'read',
    confirmation: 'always',
    requiresForeground: true,
    requiredPermissions: ['file-read'],
    timeoutMs: 120_000,
    maxConcurrency: 1,
    supportsCancellation: false,
    idempotent: false,
    resultKinds: ['file'],
  },
  {
    name: 'desktop.file.save',
    title: 'Save a text file',
    description: 'Ask the user where to save UTF-8 text generated by the agent.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['suggestedName', 'content'],
      properties: {
        suggestedName: { type: 'string', minLength: 1, maxLength: 255 },
        content: { type: 'string', maxLength: 200_000 },
      },
    },
    effect: 'write',
    confirmation: 'always',
    requiresForeground: true,
    requiredPermissions: ['file-write'],
    timeoutMs: 120_000,
    maxConcurrency: 1,
    supportsCancellation: false,
    idempotent: false,
    resultKinds: ['text'],
  },
  {
    name: 'desktop.notification.show',
    title: 'Show a notification',
    description: 'Show a bounded native desktop notification after user confirmation.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['title', 'body'],
      properties: {
        title: { type: 'string', minLength: 1, maxLength: 120 },
        body: { type: 'string', minLength: 1, maxLength: 500 },
      },
    },
    effect: 'write',
    confirmation: 'always',
    requiresForeground: true,
    requiredPermissions: ['notifications'],
    timeoutMs: 10_000,
    maxConcurrency: 1,
    supportsCancellation: false,
    idempotent: false,
    resultKinds: ['text'],
  },
  {
    name: 'desktop.clipboard.read',
    title: 'Read the clipboard',
    description: 'Read plain text from the desktop clipboard.',
    inputSchema: { type: 'object', additionalProperties: false, properties: {} },
    effect: 'read',
    confirmation: 'always',
    requiresForeground: true,
    requiredPermissions: ['clipboard-read'],
    timeoutMs: 10_000,
    maxConcurrency: 1,
    supportsCancellation: false,
    idempotent: true,
    resultKinds: ['text'],
  },
  {
    name: 'desktop.clipboard.write',
    title: 'Write to the clipboard',
    description: 'Replace the desktop clipboard with plain text.',
    inputSchema: textArgumentSchema,
    effect: 'write',
    confirmation: 'always',
    requiresForeground: true,
    requiredPermissions: ['clipboard-write'],
    timeoutMs: 10_000,
    maxConcurrency: 1,
    supportsCancellation: false,
    idempotent: true,
    resultKinds: ['text'],
  },
  {
    name: 'desktop.app.open_external',
    title: 'Open an external URL',
    description: 'Open an HTTP or HTTPS URL in the default desktop application.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: { url: { type: 'string', minLength: 1, maxLength: 2_048 } },
    },
    effect: 'write',
    confirmation: 'always',
    requiresForeground: true,
    requiredPermissions: ['open-external-url'],
    timeoutMs: 15_000,
    maxConcurrency: 1,
    supportsCancellation: false,
    idempotent: false,
    resultKinds: ['text'],
  },
];

function exactStringArgument(
  args: Record<string, unknown>,
  name: string,
  maxLength: number,
): string {
  if (Object.keys(args).length !== 1 || typeof args[name] !== 'string') {
    throw new TypeError(`Expected exactly one string argument: ${name}`);
  }
  const value = args[name];
  if (!value || value.length > maxLength) throw new TypeError(`Invalid ${name}`);
  return value;
}

function textResult(text: string): EndpointToolExecutionResult {
  return { content: [{ type: 'text', text }] };
}

function decodeBase64(value: string): Uint8Array {
  const binary = globalThis.atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
}

export async function executeDesktopEndpointTool(
  toolName: string,
  args: Record<string, unknown>,
  context: EndpointToolExecutionContext,
): Promise<EndpointToolExecutionResult> {
  const api = window.electronAPI;
  if (!api) throw new Error('Desktop bridge is unavailable');

  if (toolName === 'desktop.file.pick') {
    if (Object.keys(args).length !== 0) throw new TypeError('Expected no arguments');
    const picked = await api.file.pickEndpointFile();
    if (!picked) throw new DOMException('File selection cancelled', 'AbortError');
    const bytes = decodeBase64(picked.dataBase64);
    if (bytes.byteLength !== picked.size || bytes.byteLength > ENDPOINT_MAX_FILE_BYTES) {
      throw new Error('Selected file payload is invalid');
    }
    return { content: [await context.uploadFile({
      name: picked.name,
      mimeType: picked.mimeType,
      bytes,
    })] };
  }
  if (toolName === 'desktop.file.save') {
    const suggestedName = args.suggestedName;
    const content = args.content;
    if (
      Object.keys(args).length !== 2
      || typeof suggestedName !== 'string'
      || !suggestedName
      || suggestedName.length > 255
      || typeof content !== 'string'
      || content.length > 200_000
      || new TextEncoder().encode(content).byteLength > 200 * 1024
    ) {
      throw new TypeError('Invalid file save arguments');
    }
    const result = await api.file.saveEndpointText({ suggestedName, content });
    if (!result.saved) throw new DOMException('File save cancelled', 'AbortError');
    return textResult(`Saved ${result.name}`);
  }
  if (toolName === 'desktop.notification.show') {
    const title = args.title;
    const body = args.body;
    if (
      Object.keys(args).length !== 2
      || typeof title !== 'string'
      || !title.trim()
      || title.length > 120
      || typeof body !== 'string'
      || !body.trim()
      || body.length > 500
    ) {
      throw new TypeError('Invalid notification arguments');
    }
    if (!api.system) throw new Error('Desktop notifications are unavailable');
    const result = await api.system.showEndpointNotification({ title, body });
    if (!result.ok) {
      if (result.error === 'PERMISSION_DENIED' || result.error === 'NOTIFICATIONS_DISABLED') {
        throw new DOMException('Desktop notification permission is not granted', 'NotAllowedError');
      }
      throw new Error(`Desktop notification failed: ${result.error}`);
    }
    return textResult('Notification shown.');
  }

  if (toolName === 'desktop.clipboard.read') {
    if (Object.keys(args).length !== 0) throw new TypeError('Expected no arguments');
    if (!api.clipboard?.readText) throw new Error('Clipboard read is unavailable');
    return textResult(await api.clipboard.readText());
  }
  if (toolName === 'desktop.clipboard.write') {
    const text = exactStringArgument(args, 'text', 100_000);
    if (!api.clipboard?.writeText || !(await api.clipboard.writeText(text))) {
      throw new Error('Clipboard write failed');
    }
    return textResult('Clipboard updated.');
  }
  if (toolName === 'desktop.app.open_external') {
    const raw = exactStringArgument(args, 'url', 2_048);
    const url = new URL(raw);
    if (url.protocol !== 'http:' && url.protocol !== 'https:') {
      throw new TypeError('Only HTTP and HTTPS URLs are allowed');
    }
    if (!api.shell?.openExternalUrl) throw new Error('External URL opening is unavailable');
    const result = await api.shell.openExternalUrl(url.href);
    if (!result.ok) throw new Error(result.error);
    return textResult(`Opened ${url.href}`);
  }
  throw new TypeError(`Unknown desktop tool: ${toolName}`);
}
