import type {
  EndpointToolDefinition,
  EndpointToolExecutionResult,
} from '@xopcai/endpoint-tools-client';
import {
  ENDPOINT_FILE_OUTPUT_SCHEMA,
  ENDPOINT_MAX_FILE_BYTES,
  ENDPOINT_TEXT_OUTPUT_SCHEMA,
} from '@xopcai/endpoint-tools-protocol';

function textResult(text: string): EndpointToolExecutionResult {
  return { content: [{ type: 'text', text }] };
}

function exactStringArgument(
  args: Record<string, unknown>,
  name: string,
  maxLength: number,
): string {
  if (Object.keys(args).length !== 1 || typeof args[name] !== 'string') {
    throw new TypeError(`Expected exactly one string argument: ${name}`);
  }
  const value = args[name];
  if (!value || value.length > maxLength) throw new TypeError(`Invalid ${name}`);
  return value;
}

function decodeBase64(value: string): Uint8Array {
  const binary = globalThis.atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
}

function desktopApi() {
  const api = window.electronAPI;
  if (!api) throw new Error('Desktop bridge is unavailable');
  return api;
}

export const DESKTOP_ENDPOINT_TOOL_DEFINITIONS: readonly EndpointToolDefinition[] = [
  {
    descriptor: {
      name: 'desktop.file.pick',
      title: 'Choose a local file',
      description: 'Ask the user to choose one local file and make it available to the agent.',
      inputSchema: { type: 'object', additionalProperties: false, properties: {} },
      outputSchema: ENDPOINT_FILE_OUTPUT_SCHEMA,
      policyId: 'personal.foreground-read',
      sensitivity: 'personal',
      effect: 'read', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['file-read'], timeoutMs: 120_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['file'],
    },
    async execute(args, context) {
      if (Object.keys(args).length !== 0) throw new TypeError('Expected no arguments');
      const picked = await desktopApi().file.pickEndpointFile();
      if (!picked) throw new DOMException('File selection cancelled', 'AbortError');
      const bytes = decodeBase64(picked.dataBase64);
      if (bytes.byteLength !== picked.size || bytes.byteLength > ENDPOINT_MAX_FILE_BYTES) {
        throw new Error('Selected file payload is invalid');
      }
      return { content: [await context.uploadFile({
        name: picked.name,
        mimeType: picked.mimeType,
        bytes,
      })] };
    },
  },
  {
    descriptor: {
      name: 'desktop.file.save',
      title: 'Save a text file',
      description: 'Ask the user where to save UTF-8 text generated by the agent.',
      inputSchema: {
        type: 'object', additionalProperties: false, required: ['suggestedName', 'content'],
        properties: {
          suggestedName: { type: 'string', minLength: 1, maxLength: 255 },
          content: { type: 'string', maxLength: 200_000 },
        },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['file-write'], timeoutMs: 120_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['text'],
    },
    async execute(args) {
      const suggestedName = args.suggestedName;
      const content = args.content;
      if (
        Object.keys(args).length !== 2
        || typeof suggestedName !== 'string'
        || !suggestedName
        || suggestedName.length > 255
        || typeof content !== 'string'
        || content.length > 200_000
        || new TextEncoder().encode(content).byteLength > 200 * 1024
      ) {
        throw new TypeError('Invalid file save arguments');
      }
      const result = await desktopApi().file.saveEndpointText({ suggestedName, content });
      if (!result.saved) throw new DOMException('File save cancelled', 'AbortError');
      return textResult(`Saved ${result.name}`);
    },
  },
  {
    descriptor: {
      name: 'desktop.notification.show',
      title: 'Show a notification',
      description: 'Show a bounded native desktop notification after user confirmation.',
      inputSchema: {
        type: 'object', additionalProperties: false, required: ['title', 'body'],
        properties: {
          title: { type: 'string', minLength: 1, maxLength: 120 },
          body: { type: 'string', minLength: 1, maxLength: 500 },
        },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['notifications'], timeoutMs: 10_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['text'],
    },
    async execute(args) {
      const title = args.title;
      const body = args.body;
      if (
        Object.keys(args).length !== 2
        || typeof title !== 'string'
        || !title.trim()
        || title.length > 120
        || typeof body !== 'string'
        || !body.trim()
        || body.length > 500
      ) {
        throw new TypeError('Invalid notification arguments');
      }
      const system = desktopApi().system;
      if (!system) throw new Error('Desktop notifications are unavailable');
      const result = await system.showEndpointNotification({ title, body });
      if (!result.ok) {
        if (result.error === 'PERMISSION_DENIED' || result.error === 'NOTIFICATIONS_DISABLED') {
          throw new DOMException('Desktop notification permission is not granted', 'NotAllowedError');
        }
        throw new Error(`Desktop notification failed: ${result.error}`);
      }
      return textResult('Notification shown.');
    },
  },
  {
    descriptor: {
      name: 'desktop.clipboard.read',
      title: 'Read the clipboard',
      description: 'Read plain text from the desktop clipboard.',
      inputSchema: { type: 'object', additionalProperties: false, properties: {} },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'personal.foreground-read',
      sensitivity: 'personal',
      effect: 'read', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['clipboard-read'], timeoutMs: 10_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: true, resultKinds: ['text'],
    },
    async execute(args) {
      if (Object.keys(args).length !== 0) throw new TypeError('Expected no arguments');
      const clipboard = desktopApi().clipboard;
      if (!clipboard?.readText) throw new Error('Clipboard read is unavailable');
      return textResult(await clipboard.readText());
    },
  },
  {
    descriptor: {
      name: 'desktop.clipboard.write',
      title: 'Write to the clipboard',
      description: 'Replace the desktop clipboard with plain text.',
      inputSchema: {
        type: 'object', additionalProperties: false, required: ['text'],
        properties: { text: { type: 'string', minLength: 1, maxLength: 100_000 } },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['clipboard-write'], timeoutMs: 10_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: true, resultKinds: ['text'],
    },
    async execute(args) {
      const text = exactStringArgument(args, 'text', 100_000);
      const clipboard = desktopApi().clipboard;
      if (!clipboard?.writeText || !(await clipboard.writeText(text))) {
        throw new Error('Clipboard write failed');
      }
      return textResult('Clipboard updated.');
    },
  },
  {
    descriptor: {
      name: 'desktop.app.open_external',
      title: 'Open an external URL',
      description: 'Open an HTTP or HTTPS URL in the default desktop application.',
      inputSchema: {
        type: 'object', additionalProperties: false, required: ['url'],
        properties: { url: { type: 'string', minLength: 1, maxLength: 2_048 } },
      },
      outputSchema: ENDPOINT_TEXT_OUTPUT_SCHEMA,
      policyId: 'user.foreground-write',
      sensitivity: 'personal',
      effect: 'write', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['open-external-url'], timeoutMs: 15_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['text'],
    },
    async execute(args) {
      const raw = exactStringArgument(args, 'url', 2_048);
      const url = new URL(raw);
      if (url.protocol !== 'http:' && url.protocol !== 'https:') {
        throw new TypeError('Only HTTP and HTTPS URLs are allowed');
      }
      const shell = desktopApi().shell;
      if (!shell?.openExternalUrl) throw new Error('External URL opening is unavailable');
      const result = await shell.openExternalUrl(url.href);
      if (!result.ok) throw new Error(result.error);
      return textResult(`Opened ${url.href}`);
    },
  },
];
