import type {
  EndpointToolDefinition,
  EndpointToolExecutionResult,
} from '@xopcai/endpoint-tools-client';
import { ENDPOINT_MAX_FILE_BYTES } from '@xopcai/endpoint-tools-protocol';

function textResult(text: string): EndpointToolExecutionResult {
  return { content: [{ type: 'text', text }] };
}

function requireUserActivation(): void {
  if (!navigator.userActivation?.isActive) {
    throw new DOMException('A current user gesture is required', 'NotAllowedError');
  }
}

function userCancelled(message: string): DOMException {
  return new DOMException(message, 'AbortError');
}

function safeSuggestedName(args: Record<string, unknown>): { suggestedName: string; content: string } {
  const suggestedName = args.suggestedName;
  const content = args.content;
  if (
    Object.keys(args).length !== 2
    || typeof suggestedName !== 'string'
    || !suggestedName
    || suggestedName === '.'
    || suggestedName === '..'
    || suggestedName.length > 255
    || suggestedName.includes('/')
    || suggestedName.includes('\\')
    || typeof content !== 'string'
    || content.length > 200_000
    || new TextEncoder().encode(content).byteLength > 200 * 1024
  ) {
    throw new TypeError('Invalid file download arguments');
  }
  return { suggestedName, content };
}

function pickBrowserFile(): Promise<File> {
  requireUserActivation();
  return new Promise((resolve, reject) => {
    const input = document.createElement('input');
    input.type = 'file';
    input.multiple = false;
    input.onchange = () => {
      const file = input.files?.[0];
      if (file) resolve(file);
      else reject(userCancelled('File selection cancelled'));
    };
    input.oncancel = () => reject(userCancelled('File selection cancelled'));
    input.click();
  });
}

function requireString(args: Record<string, unknown>, key: string): string {
  const value = args[key];
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError(`${key} must be a non-empty string`);
  }
  return value;
}

function requireExactKeys(args: Record<string, unknown>, keys: string[]): void {
  const actual = Object.keys(args).toSorted();
  const expected = keys.toSorted();
  if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) {
    throw new TypeError(`arguments must contain exactly: ${expected.join(', ') || 'no fields'}`);
  }
}

export const WEB_ENDPOINT_TOOL_DEFINITIONS: readonly EndpointToolDefinition[] = [
  {
    descriptor: {
      name: 'web.file.pick',
      title: 'Choose a local file',
      description: 'Ask the user to choose one browser-accessible file and make it available to the agent.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      effect: 'read', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['file-read'], timeoutMs: 120_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['file'],
    },
    async execute(args, context) {
      requireExactKeys(args, []);
      const file = await pickBrowserFile();
      if (file.size > ENDPOINT_MAX_FILE_BYTES) {
        throw new TypeError(`Selected file exceeds ${ENDPOINT_MAX_FILE_BYTES} bytes`);
      }
      const bytes = new Uint8Array(await file.arrayBuffer());
      if (bytes.byteLength !== file.size || bytes.byteLength > ENDPOINT_MAX_FILE_BYTES) {
        throw new Error('Selected file payload is invalid');
      }
      return { content: [await context.uploadFile({
        name: file.name,
        mimeType: file.type || 'application/octet-stream',
        bytes,
      })] };
    },
  },
  {
    descriptor: {
      name: 'web.file.download',
      title: 'Download a text file',
      description: 'Download bounded UTF-8 text generated by the agent through this browser.',
      inputSchema: {
        type: 'object',
        properties: {
          suggestedName: { type: 'string', minLength: 1, maxLength: 255 },
          content: { type: 'string', maxLength: 200_000 },
        },
        required: ['suggestedName', 'content'],
        additionalProperties: false,
      },
      effect: 'write', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['file-download'], timeoutMs: 30_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['text'],
    },
    async execute(args) {
      const { suggestedName, content } = safeSuggestedName(args);
      requireUserActivation();
      const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' }));
      try {
        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.download = suggestedName;
        anchor.click();
      } finally {
        URL.revokeObjectURL(url);
      }
      return textResult(`Download started: ${suggestedName}`);
    },
  },
  {
    descriptor: {
      name: 'web.page.get_selection',
      title: 'Read selected text',
      description: 'Read the text currently selected in this browser tab.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      effect: 'read', confirmation: 'never', requiresForeground: true,
      requiredPermissions: [], timeoutMs: 10_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: true, resultKinds: ['text'],
    },
    async execute(args) {
      requireExactKeys(args, []);
      return textResult(window.getSelection()?.toString() ?? '');
    },
  },
  {
    descriptor: {
      name: 'web.clipboard.write',
      title: 'Write clipboard',
      description: 'Write text to the clipboard from this browser tab.',
      inputSchema: {
        type: 'object', properties: { text: { type: 'string', maxLength: 100_000 } },
        required: ['text'], additionalProperties: false,
      },
      effect: 'write', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['clipboard-write'], timeoutMs: 30_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: true, resultKinds: ['text'],
    },
    async execute(args) {
      requireExactKeys(args, ['text']);
      if (!navigator.clipboard || !document.hasFocus()) {
        throw new DOMException('Clipboard access requires a focused browser tab', 'NotAllowedError');
      }
      const text = requireString(args, 'text');
      if (text.length > 100_000) throw new TypeError('text exceeds 100000 characters');
      await navigator.clipboard.writeText(text);
      return textResult('Clipboard updated.');
    },
  },
  {
    descriptor: {
      name: 'web.page.navigate',
      title: 'Navigate page',
      description: 'Navigate this browser tab to an HTTP or HTTPS URL.',
      inputSchema: {
        type: 'object', properties: { url: { type: 'string', maxLength: 4_096 } },
        required: ['url'], additionalProperties: false,
      },
      effect: 'destructive', confirmation: 'always', requiresForeground: true,
      requiredPermissions: ['navigation'], timeoutMs: 30_000, maxConcurrency: 1,
      supportsCancellation: false, idempotent: false, resultKinds: ['text'],
    },
    async execute(args) {
      requireExactKeys(args, ['url']);
      const rawUrl = requireString(args, 'url');
      if (rawUrl.length > 4_096) throw new TypeError('url exceeds 4096 characters');
      const target = new URL(rawUrl, window.location.href);
      if (target.protocol !== 'http:' && target.protocol !== 'https:') {
        throw new TypeError('url must use HTTP or HTTPS');
      }
      return {
        content: [{ type: 'text', text: `Navigating to ${target.href}` }],
        afterSend: () => window.location.assign(target.href),
      };
    },
  },
];
