export type UsageTotals = {
  calls: number;
  succeededCalls: number;
  failedCalls: number;
  unknownCostCalls: number;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  totalTokens: number;
  knownCostUsd: string;
  costCompleteness: 'complete' | 'partial' | 'unknown';
};

export type UsageEvent = {
  id: string;
  traceId: string;
  parentEventId?: string;
  conversationId?: string;
  runId?: string;
  agentId?: string;
  category: string;
  operation: string;
  trigger: string;
  reasonKey: string;
  provider: string;
  model: string;
  status: string;
  startedAt: number;
  finishedAt?: number;
  durationMs?: number;
  inputTokens?: number;
  outputTokens?: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  reasoningTokens?: number;
  totalTokens?: number;
  estimatedCostUsd?: string;
  costSource: string;
  pricingSnapshot?: { input: number; output: number; cacheRead: number; cacheWrite: number };
  errorSummary?: string;
};
